import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "bst",
    category: "data-structures",
    title: "Binary Search Trees",
    description: "Practice BST ordering, search, insertion, deletion, and traversal properties.",
    accent: "green",
    questionIds: ["bst-01", "bst-02", "bst-03", "bst-04", "bst-05", "bst-06", "bst-07", "bst-08", "bst-09", "bst-10", "bst-11", "bst-12", "bst-13", "bst-14", "bst-15", "bst-16", "bst-17", "bst-18", "bst-19", "bst-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "bst-01",
    topicId: "bst",
    prompt: "Which statement best describes the core purpose of Binary Search Trees?",
    options: ["ordered subtrees allow directed search and inorder traversal yields sorted keys", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "ordered subtrees allow directed search and inorder traversal yields sorted keys This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-02",
    topicId: "bst",
    prompt: "Which interview clue most strongly suggests considering Binary Search Trees?",
    options: ["Always memorize one canonical implementation and use it unchanged", "tree nodes obey a left-smaller/right-larger ordering rule", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "tree nodes obey a left-smaller/right-larger ordering rule This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-03",
    topicId: "bst",
    prompt: "What is the most useful invariant to maintain when applying Binary Search Trees?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Binary Search Trees algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Binary Search Trees algorithm progresses This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-04",
    topicId: "bst",
    prompt: "When using a standard efficient implementation of Binary Search Trees, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-05",
    topicId: "bst",
    prompt: "Which memory cost is easiest to overlook when reasoning about Binary Search Trees?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-06",
    topicId: "bst",
    prompt: "Which edge case should be checked explicitly in a robust Binary Search Trees solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-07",
    topicId: "bst",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Binary Search Trees solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-08",
    topicId: "bst",
    prompt: "What is the best reason to compare Binary Search Trees with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-09",
    topicId: "bst",
    prompt: "Which input property can materially change how you implement Binary Search Trees?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-10",
    topicId: "bst",
    prompt: "What should algorithmic state represent in a clean Binary Search Trees solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-11",
    topicId: "bst",
    prompt: "What should guarantee termination in an iterative or recursive use of Binary Search Trees?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-12",
    topicId: "bst",
    prompt: "What is the strongest way to reason about correctness for Binary Search Trees in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-13",
    topicId: "bst",
    prompt: "Before optimizing a working Binary Search Trees solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-14",
    topicId: "bst",
    prompt: "Which implementation habit most improves reliability for Binary Search Trees?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-15",
    topicId: "bst",
    prompt: "Which test strategy is most useful for validating a Binary Search Trees implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-16",
    topicId: "bst",
    prompt: "When should you avoid forcing Binary Search Trees onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Binary Search Trees correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Binary Search Trees correct or efficient This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-17",
    topicId: "bst",
    prompt: "When explaining a Binary Search Trees solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-18",
    topicId: "bst",
    prompt: "Why should constraints be examined before selecting Binary Search Trees?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-19",
    topicId: "bst",
    prompt: "What is the main value of dry-running a Binary Search Trees solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Binary Search Trees.",
  },
  {
    id: "bst-20",
    topicId: "bst",
    prompt: "After solving a Binary Search Trees problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Binary Search Trees.",
  },
];
