import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "graphs",
    category: "data-structures",
    title: "Graphs",
    description: "Review representations, traversal, connectivity, cycles, and graph modeling.",
    accent: "green",
    questionIds: ["graphs-01", "graphs-02", "graphs-03", "graphs-04", "graphs-05", "graphs-06", "graphs-07", "graphs-08", "graphs-09", "graphs-10", "graphs-11", "graphs-12", "graphs-13", "graphs-14", "graphs-15", "graphs-16", "graphs-17", "graphs-18", "graphs-19", "graphs-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "graphs-01",
    topicId: "graphs",
    prompt: "Which statement best describes the core purpose of Graphs?",
    options: ["vertices and edges model arbitrary relationships and connectivity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "vertices and edges model arbitrary relationships and connectivity This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-02",
    topicId: "graphs",
    prompt: "Which interview clue most strongly suggests considering Graphs?",
    options: ["Always memorize one canonical implementation and use it unchanged", "entities have many-to-many relationships, dependencies, routes, or connections", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "entities have many-to-many relationships, dependencies, routes, or connections This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-03",
    topicId: "graphs",
    prompt: "What is the most useful invariant to maintain when applying Graphs?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Graphs algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Graphs algorithm progresses This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-04",
    topicId: "graphs",
    prompt: "When using a standard efficient implementation of Graphs, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-05",
    topicId: "graphs",
    prompt: "Which memory cost is easiest to overlook when reasoning about Graphs?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-06",
    topicId: "graphs",
    prompt: "Which edge case should be checked explicitly in a robust Graphs solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-07",
    topicId: "graphs",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Graphs solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-08",
    topicId: "graphs",
    prompt: "What is the best reason to compare Graphs with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-09",
    topicId: "graphs",
    prompt: "Which input property can materially change how you implement Graphs?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-10",
    topicId: "graphs",
    prompt: "What should algorithmic state represent in a clean Graphs solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-11",
    topicId: "graphs",
    prompt: "What should guarantee termination in an iterative or recursive use of Graphs?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-12",
    topicId: "graphs",
    prompt: "What is the strongest way to reason about correctness for Graphs in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-13",
    topicId: "graphs",
    prompt: "Before optimizing a working Graphs solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-14",
    topicId: "graphs",
    prompt: "Which implementation habit most improves reliability for Graphs?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-15",
    topicId: "graphs",
    prompt: "Which test strategy is most useful for validating a Graphs implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-16",
    topicId: "graphs",
    prompt: "When should you avoid forcing Graphs onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Graphs correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Graphs correct or efficient This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-17",
    topicId: "graphs",
    prompt: "When explaining a Graphs solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-18",
    topicId: "graphs",
    prompt: "Why should constraints be examined before selecting Graphs?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-19",
    topicId: "graphs",
    prompt: "What is the main value of dry-running a Graphs solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Graphs.",
  },
  {
    id: "graphs-20",
    topicId: "graphs",
    prompt: "After solving a Graphs problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Graphs.",
  },
];
