import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "heap-priority-queue",
    category: "data-structures",
    title: "Heap / Priority Queue",
    description: "Practice top-k, scheduling, streaming, and priority-based processing.",
    accent: "green",
    questionIds: ["heap-priority-queue-01", "heap-priority-queue-02", "heap-priority-queue-03", "heap-priority-queue-04", "heap-priority-queue-05", "heap-priority-queue-06", "heap-priority-queue-07", "heap-priority-queue-08", "heap-priority-queue-09", "heap-priority-queue-10", "heap-priority-queue-11", "heap-priority-queue-12", "heap-priority-queue-13", "heap-priority-queue-14", "heap-priority-queue-15", "heap-priority-queue-16", "heap-priority-queue-17", "heap-priority-queue-18", "heap-priority-queue-19", "heap-priority-queue-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "heap-priority-queue-01",
    topicId: "heap-priority-queue",
    prompt: "Which statement best describes the core purpose of Heap / Priority Queue?",
    options: ["the highest- or lowest-priority item can be repeatedly accessed efficiently", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "the highest- or lowest-priority item can be repeatedly accessed efficiently This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-02",
    topicId: "heap-priority-queue",
    prompt: "Which interview clue most strongly suggests considering Heap / Priority Queue?",
    options: ["Always memorize one canonical implementation and use it unchanged", "you repeatedly need the current min, max, or top-k boundary", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "you repeatedly need the current min, max, or top-k boundary This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-03",
    topicId: "heap-priority-queue",
    prompt: "What is the most useful invariant to maintain when applying Heap / Priority Queue?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Heap / Priority Queue algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Heap / Priority Queue algorithm progresses This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-04",
    topicId: "heap-priority-queue",
    prompt: "When using a standard efficient implementation of Heap / Priority Queue, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-05",
    topicId: "heap-priority-queue",
    prompt: "Which memory cost is easiest to overlook when reasoning about Heap / Priority Queue?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-06",
    topicId: "heap-priority-queue",
    prompt: "Which edge case should be checked explicitly in a robust Heap / Priority Queue solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-07",
    topicId: "heap-priority-queue",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Heap / Priority Queue solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-08",
    topicId: "heap-priority-queue",
    prompt: "What is the best reason to compare Heap / Priority Queue with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-09",
    topicId: "heap-priority-queue",
    prompt: "Which input property can materially change how you implement Heap / Priority Queue?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-10",
    topicId: "heap-priority-queue",
    prompt: "What should algorithmic state represent in a clean Heap / Priority Queue solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-11",
    topicId: "heap-priority-queue",
    prompt: "What should guarantee termination in an iterative or recursive use of Heap / Priority Queue?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-12",
    topicId: "heap-priority-queue",
    prompt: "What is the strongest way to reason about correctness for Heap / Priority Queue in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-13",
    topicId: "heap-priority-queue",
    prompt: "Before optimizing a working Heap / Priority Queue solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-14",
    topicId: "heap-priority-queue",
    prompt: "Which implementation habit most improves reliability for Heap / Priority Queue?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-15",
    topicId: "heap-priority-queue",
    prompt: "Which test strategy is most useful for validating a Heap / Priority Queue implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-16",
    topicId: "heap-priority-queue",
    prompt: "When should you avoid forcing Heap / Priority Queue onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Heap / Priority Queue correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Heap / Priority Queue correct or efficient This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-17",
    topicId: "heap-priority-queue",
    prompt: "When explaining a Heap / Priority Queue solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-18",
    topicId: "heap-priority-queue",
    prompt: "Why should constraints be examined before selecting Heap / Priority Queue?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-19",
    topicId: "heap-priority-queue",
    prompt: "What is the main value of dry-running a Heap / Priority Queue solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
  {
    id: "heap-priority-queue-20",
    topicId: "heap-priority-queue",
    prompt: "After solving a Heap / Priority Queue problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Heap / Priority Queue.",
  },
];
