import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "linked-list",
    category: "data-structures",
    title: "Linked Lists",
    description: "Practice pointer manipulation, reversal, cycle detection, and list restructuring.",
    accent: "blue",
    questionIds: ["linked-list-01", "linked-list-02", "linked-list-03", "linked-list-04", "linked-list-05", "linked-list-06", "linked-list-07", "linked-list-08", "linked-list-09", "linked-list-10", "linked-list-11", "linked-list-12", "linked-list-13", "linked-list-14", "linked-list-15", "linked-list-16", "linked-list-17", "linked-list-18", "linked-list-19", "linked-list-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "linked-list-01",
    topicId: "linked-list",
    prompt: "Which statement best describes the core purpose of Linked Lists?",
    options: ["nodes are connected by references, so pointer rewiring changes structure without shifting elements", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "nodes are connected by references, so pointer rewiring changes structure without shifting elements This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-02",
    topicId: "linked-list",
    prompt: "Which interview clue most strongly suggests considering Linked Lists?",
    options: ["Always memorize one canonical implementation and use it unchanged", "the problem emphasizes node relationships rather than random indexing", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "the problem emphasizes node relationships rather than random indexing This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-03",
    topicId: "linked-list",
    prompt: "What is the most useful invariant to maintain when applying Linked Lists?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Linked Lists algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Linked Lists algorithm progresses This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-04",
    topicId: "linked-list",
    prompt: "When using a standard efficient implementation of Linked Lists, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-05",
    topicId: "linked-list",
    prompt: "Which memory cost is easiest to overlook when reasoning about Linked Lists?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-06",
    topicId: "linked-list",
    prompt: "Which edge case should be checked explicitly in a robust Linked Lists solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-07",
    topicId: "linked-list",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Linked Lists solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-08",
    topicId: "linked-list",
    prompt: "What is the best reason to compare Linked Lists with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-09",
    topicId: "linked-list",
    prompt: "Which input property can materially change how you implement Linked Lists?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-10",
    topicId: "linked-list",
    prompt: "What should algorithmic state represent in a clean Linked Lists solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-11",
    topicId: "linked-list",
    prompt: "What should guarantee termination in an iterative or recursive use of Linked Lists?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-12",
    topicId: "linked-list",
    prompt: "What is the strongest way to reason about correctness for Linked Lists in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-13",
    topicId: "linked-list",
    prompt: "Before optimizing a working Linked Lists solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-14",
    topicId: "linked-list",
    prompt: "Which implementation habit most improves reliability for Linked Lists?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-15",
    topicId: "linked-list",
    prompt: "Which test strategy is most useful for validating a Linked Lists implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-16",
    topicId: "linked-list",
    prompt: "When should you avoid forcing Linked Lists onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Linked Lists correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Linked Lists correct or efficient This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-17",
    topicId: "linked-list",
    prompt: "When explaining a Linked Lists solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-18",
    topicId: "linked-list",
    prompt: "Why should constraints be examined before selecting Linked Lists?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-19",
    topicId: "linked-list",
    prompt: "What is the main value of dry-running a Linked Lists solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Linked Lists.",
  },
  {
    id: "linked-list-20",
    topicId: "linked-list",
    prompt: "After solving a Linked Lists problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Linked Lists.",
  },
];
