import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "queue-deque",
    category: "data-structures",
    title: "Queue & Deque",
    description: "Review FIFO processing, deques, BFS usage, and window techniques.",
    accent: "amber",
    questionIds: ["queue-deque-01", "queue-deque-02", "queue-deque-03", "queue-deque-04", "queue-deque-05", "queue-deque-06", "queue-deque-07", "queue-deque-08", "queue-deque-09", "queue-deque-10", "queue-deque-11", "queue-deque-12", "queue-deque-13", "queue-deque-14", "queue-deque-15", "queue-deque-16", "queue-deque-17", "queue-deque-18", "queue-deque-19", "queue-deque-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "queue-deque-01",
    topicId: "queue-deque",
    prompt: "Which statement best describes the core purpose of Queue & Deque?",
    options: ["FIFO or double-ended access controls processing order efficiently", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "FIFO or double-ended access controls processing order efficiently This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-02",
    topicId: "queue-deque",
    prompt: "Which interview clue most strongly suggests considering Queue & Deque?",
    options: ["Always memorize one canonical implementation and use it unchanged", "work must be processed by arrival order or both ends are useful", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "work must be processed by arrival order or both ends are useful This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-03",
    topicId: "queue-deque",
    prompt: "What is the most useful invariant to maintain when applying Queue & Deque?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Queue & Deque algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Queue & Deque algorithm progresses This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-04",
    topicId: "queue-deque",
    prompt: "When using a standard efficient implementation of Queue & Deque, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-05",
    topicId: "queue-deque",
    prompt: "Which memory cost is easiest to overlook when reasoning about Queue & Deque?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-06",
    topicId: "queue-deque",
    prompt: "Which edge case should be checked explicitly in a robust Queue & Deque solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-07",
    topicId: "queue-deque",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Queue & Deque solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-08",
    topicId: "queue-deque",
    prompt: "What is the best reason to compare Queue & Deque with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-09",
    topicId: "queue-deque",
    prompt: "Which input property can materially change how you implement Queue & Deque?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-10",
    topicId: "queue-deque",
    prompt: "What should algorithmic state represent in a clean Queue & Deque solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-11",
    topicId: "queue-deque",
    prompt: "What should guarantee termination in an iterative or recursive use of Queue & Deque?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-12",
    topicId: "queue-deque",
    prompt: "What is the strongest way to reason about correctness for Queue & Deque in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-13",
    topicId: "queue-deque",
    prompt: "Before optimizing a working Queue & Deque solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-14",
    topicId: "queue-deque",
    prompt: "Which implementation habit most improves reliability for Queue & Deque?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-15",
    topicId: "queue-deque",
    prompt: "Which test strategy is most useful for validating a Queue & Deque implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-16",
    topicId: "queue-deque",
    prompt: "When should you avoid forcing Queue & Deque onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Queue & Deque correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Queue & Deque correct or efficient This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-17",
    topicId: "queue-deque",
    prompt: "When explaining a Queue & Deque solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-18",
    topicId: "queue-deque",
    prompt: "Why should constraints be examined before selecting Queue & Deque?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-19",
    topicId: "queue-deque",
    prompt: "What is the main value of dry-running a Queue & Deque solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Queue & Deque.",
  },
  {
    id: "queue-deque-20",
    topicId: "queue-deque",
    prompt: "After solving a Queue & Deque problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Queue & Deque.",
  },
];
