import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "stack",
    category: "data-structures",
    title: "Stack",
    description: "Review LIFO behavior, parsing, monotonic stacks, and interview applications.",
    accent: "green",
    questionIds: ["stack-01", "stack-02", "stack-03", "stack-04", "stack-05", "stack-06", "stack-07", "stack-08", "stack-09", "stack-10", "stack-11", "stack-12", "stack-13", "stack-14", "stack-15", "stack-16", "stack-17", "stack-18", "stack-19", "stack-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "stack-01",
    topicId: "stack",
    prompt: "Which statement best describes the core purpose of Stack?",
    options: ["LIFO order preserves the most recent unresolved item", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "LIFO order preserves the most recent unresolved item This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-02",
    topicId: "stack",
    prompt: "Which interview clue most strongly suggests considering Stack?",
    options: ["Always memorize one canonical implementation and use it unchanged", "nested structure, undo behavior, or nearest unresolved element matters", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "nested structure, undo behavior, or nearest unresolved element matters This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-03",
    topicId: "stack",
    prompt: "What is the most useful invariant to maintain when applying Stack?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Stack algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Stack algorithm progresses This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-04",
    topicId: "stack",
    prompt: "When using a standard efficient implementation of Stack, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-05",
    topicId: "stack",
    prompt: "Which memory cost is easiest to overlook when reasoning about Stack?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-06",
    topicId: "stack",
    prompt: "Which edge case should be checked explicitly in a robust Stack solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-07",
    topicId: "stack",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Stack solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-08",
    topicId: "stack",
    prompt: "What is the best reason to compare Stack with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-09",
    topicId: "stack",
    prompt: "Which input property can materially change how you implement Stack?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-10",
    topicId: "stack",
    prompt: "What should algorithmic state represent in a clean Stack solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-11",
    topicId: "stack",
    prompt: "What should guarantee termination in an iterative or recursive use of Stack?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-12",
    topicId: "stack",
    prompt: "What is the strongest way to reason about correctness for Stack in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-13",
    topicId: "stack",
    prompt: "Before optimizing a working Stack solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-14",
    topicId: "stack",
    prompt: "Which implementation habit most improves reliability for Stack?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-15",
    topicId: "stack",
    prompt: "Which test strategy is most useful for validating a Stack implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-16",
    topicId: "stack",
    prompt: "When should you avoid forcing Stack onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Stack correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Stack correct or efficient This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-17",
    topicId: "stack",
    prompt: "When explaining a Stack solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-18",
    topicId: "stack",
    prompt: "Why should constraints be examined before selecting Stack?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-19",
    topicId: "stack",
    prompt: "What is the main value of dry-running a Stack solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Stack.",
  },
  {
    id: "stack-20",
    topicId: "stack",
    prompt: "After solving a Stack problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Stack.",
  },
];
