import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "trees",
    category: "data-structures",
    title: "Trees",
    description: "Review tree terminology, recursive structure, traversals, and common interview reasoning.",
    accent: "coral",
    questionIds: ["trees-01", "trees-02", "trees-03", "trees-04", "trees-05", "trees-06", "trees-07", "trees-08", "trees-09", "trees-10", "trees-11", "trees-12", "trees-13", "trees-14", "trees-15", "trees-16", "trees-17", "trees-18", "trees-19", "trees-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "trees-01",
    topicId: "trees",
    prompt: "Which statement best describes the core purpose of Trees?",
    options: ["recursive parent-child structure naturally decomposes into subtrees", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "recursive parent-child structure naturally decomposes into subtrees This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-02",
    topicId: "trees",
    prompt: "Which interview clue most strongly suggests considering Trees?",
    options: ["Always memorize one canonical implementation and use it unchanged", "the input is hierarchical and each node leads to child subproblems", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "the input is hierarchical and each node leads to child subproblems This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-03",
    topicId: "trees",
    prompt: "What is the most useful invariant to maintain when applying Trees?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Trees algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Trees algorithm progresses This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-04",
    topicId: "trees",
    prompt: "When using a standard efficient implementation of Trees, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-05",
    topicId: "trees",
    prompt: "Which memory cost is easiest to overlook when reasoning about Trees?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-06",
    topicId: "trees",
    prompt: "Which edge case should be checked explicitly in a robust Trees solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-07",
    topicId: "trees",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Trees solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-08",
    topicId: "trees",
    prompt: "What is the best reason to compare Trees with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-09",
    topicId: "trees",
    prompt: "Which input property can materially change how you implement Trees?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-10",
    topicId: "trees",
    prompt: "What should algorithmic state represent in a clean Trees solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-11",
    topicId: "trees",
    prompt: "What should guarantee termination in an iterative or recursive use of Trees?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-12",
    topicId: "trees",
    prompt: "What is the strongest way to reason about correctness for Trees in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-13",
    topicId: "trees",
    prompt: "Before optimizing a working Trees solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-14",
    topicId: "trees",
    prompt: "Which implementation habit most improves reliability for Trees?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-15",
    topicId: "trees",
    prompt: "Which test strategy is most useful for validating a Trees implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-16",
    topicId: "trees",
    prompt: "When should you avoid forcing Trees onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Trees correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Trees correct or efficient This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-17",
    topicId: "trees",
    prompt: "When explaining a Trees solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-18",
    topicId: "trees",
    prompt: "Why should constraints be examined before selecting Trees?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-19",
    topicId: "trees",
    prompt: "What is the main value of dry-running a Trees solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Trees.",
  },
  {
    id: "trees-20",
    topicId: "trees",
    prompt: "After solving a Trees problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Trees.",
  },
];
