import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "tries",
    category: "data-structures",
    title: "Tries",
    description: "Understand prefix trees, operations, complexity, and string-search applications.",
    accent: "coral",
    questionIds: ["tries-01", "tries-02", "tries-03", "tries-04", "tries-05", "tries-06", "tries-07", "tries-08", "tries-09", "tries-10", "tries-11", "tries-12", "tries-13", "tries-14", "tries-15", "tries-16", "tries-17", "tries-18", "tries-19", "tries-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "tries-01",
    topicId: "tries",
    prompt: "Which statement best describes the core purpose of Tries?",
    options: ["characters are stored along prefix paths so shared prefixes reuse structure", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "characters are stored along prefix paths so shared prefixes reuse structure This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-02",
    topicId: "tries",
    prompt: "Which interview clue most strongly suggests considering Tries?",
    options: ["Always memorize one canonical implementation and use it unchanged", "prefix lookup or dictionary search dominates", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "prefix lookup or dictionary search dominates This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-03",
    topicId: "tries",
    prompt: "What is the most useful invariant to maintain when applying Tries?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Tries algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Tries algorithm progresses This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-04",
    topicId: "tries",
    prompt: "When using a standard efficient implementation of Tries, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-05",
    topicId: "tries",
    prompt: "Which memory cost is easiest to overlook when reasoning about Tries?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-06",
    topicId: "tries",
    prompt: "Which edge case should be checked explicitly in a robust Tries solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-07",
    topicId: "tries",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Tries solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-08",
    topicId: "tries",
    prompt: "What is the best reason to compare Tries with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-09",
    topicId: "tries",
    prompt: "Which input property can materially change how you implement Tries?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-10",
    topicId: "tries",
    prompt: "What should algorithmic state represent in a clean Tries solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-11",
    topicId: "tries",
    prompt: "What should guarantee termination in an iterative or recursive use of Tries?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-12",
    topicId: "tries",
    prompt: "What is the strongest way to reason about correctness for Tries in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-13",
    topicId: "tries",
    prompt: "Before optimizing a working Tries solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-14",
    topicId: "tries",
    prompt: "Which implementation habit most improves reliability for Tries?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-15",
    topicId: "tries",
    prompt: "Which test strategy is most useful for validating a Tries implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-16",
    topicId: "tries",
    prompt: "When should you avoid forcing Tries onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Tries correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Tries correct or efficient This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-17",
    topicId: "tries",
    prompt: "When explaining a Tries solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-18",
    topicId: "tries",
    prompt: "Why should constraints be examined before selecting Tries?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-19",
    topicId: "tries",
    prompt: "What is the main value of dry-running a Tries solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Tries.",
  },
  {
    id: "tries-20",
    topicId: "tries",
    prompt: "After solving a Tries problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Tries.",
  },
];
