import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "amortized-analysis",
    category: "big-o",
    title: "Amortized Analysis",
    description: "Understand aggregate costs such as dynamic arrays and stack-based techniques.",
    accent: "blue",
    questionIds: ["amortized-analysis-01", "amortized-analysis-02", "amortized-analysis-03", "amortized-analysis-04", "amortized-analysis-05", "amortized-analysis-06", "amortized-analysis-07", "amortized-analysis-08", "amortized-analysis-09", "amortized-analysis-10", "amortized-analysis-11", "amortized-analysis-12", "amortized-analysis-13", "amortized-analysis-14", "amortized-analysis-15", "amortized-analysis-16", "amortized-analysis-17", "amortized-analysis-18", "amortized-analysis-19", "amortized-analysis-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "amortized-analysis-01",
    topicId: "amortized-analysis",
    prompt: "Which statement best describes the core purpose of Amortized Analysis?",
    options: ["rare expensive operations are averaged over a sequence of operations", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "rare expensive operations are averaged over a sequence of operations This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-02",
    topicId: "amortized-analysis",
    prompt: "Which interview clue most strongly suggests considering Amortized Analysis?",
    options: ["Always memorize one canonical implementation and use it unchanged", "an operation is usually cheap but occasionally triggers costly resizing or cleanup", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "an operation is usually cheap but occasionally triggers costly resizing or cleanup This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-03",
    topicId: "amortized-analysis",
    prompt: "What is the most useful invariant to maintain when applying Amortized Analysis?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Amortized Analysis algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Amortized Analysis algorithm progresses This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-04",
    topicId: "amortized-analysis",
    prompt: "When using a standard efficient implementation of Amortized Analysis, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-05",
    topicId: "amortized-analysis",
    prompt: "Which memory cost is easiest to overlook when reasoning about Amortized Analysis?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-06",
    topicId: "amortized-analysis",
    prompt: "Which edge case should be checked explicitly in a robust Amortized Analysis solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-07",
    topicId: "amortized-analysis",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Amortized Analysis solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-08",
    topicId: "amortized-analysis",
    prompt: "What is the best reason to compare Amortized Analysis with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-09",
    topicId: "amortized-analysis",
    prompt: "Which input property can materially change how you implement Amortized Analysis?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-10",
    topicId: "amortized-analysis",
    prompt: "What should algorithmic state represent in a clean Amortized Analysis solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-11",
    topicId: "amortized-analysis",
    prompt: "What should guarantee termination in an iterative or recursive use of Amortized Analysis?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-12",
    topicId: "amortized-analysis",
    prompt: "What is the strongest way to reason about correctness for Amortized Analysis in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-13",
    topicId: "amortized-analysis",
    prompt: "Before optimizing a working Amortized Analysis solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-14",
    topicId: "amortized-analysis",
    prompt: "Which implementation habit most improves reliability for Amortized Analysis?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-15",
    topicId: "amortized-analysis",
    prompt: "Which test strategy is most useful for validating a Amortized Analysis implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-16",
    topicId: "amortized-analysis",
    prompt: "When should you avoid forcing Amortized Analysis onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Amortized Analysis correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Amortized Analysis correct or efficient This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-17",
    topicId: "amortized-analysis",
    prompt: "When explaining a Amortized Analysis solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-18",
    topicId: "amortized-analysis",
    prompt: "Why should constraints be examined before selecting Amortized Analysis?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-19",
    topicId: "amortized-analysis",
    prompt: "What is the main value of dry-running a Amortized Analysis solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Amortized Analysis.",
  },
  {
    id: "amortized-analysis-20",
    topicId: "amortized-analysis",
    prompt: "After solving a Amortized Analysis problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Amortized Analysis.",
  },
];
