import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "complexity-analysis",
    category: "big-o",
    title: "Big-O Fundamentals",
    description: "Analyze time and space complexity precisely across common code patterns.",
    accent: "amber",
    questionIds: ["complexity-analysis-01", "complexity-analysis-02", "complexity-analysis-03", "complexity-analysis-04", "complexity-analysis-05", "complexity-analysis-06", "complexity-analysis-07", "complexity-analysis-08", "complexity-analysis-09", "complexity-analysis-10", "complexity-analysis-11", "complexity-analysis-12", "complexity-analysis-13", "complexity-analysis-14", "complexity-analysis-15", "complexity-analysis-16", "complexity-analysis-17", "complexity-analysis-18", "complexity-analysis-19", "complexity-analysis-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "complexity-analysis-01",
    topicId: "complexity-analysis",
    prompt: "Which statement best describes the core purpose of Big-O Fundamentals?",
    options: ["growth is expressed as input size increases while constants and lower-order terms are ignored", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "growth is expressed as input size increases while constants and lower-order terms are ignored This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-02",
    topicId: "complexity-analysis",
    prompt: "Which interview clue most strongly suggests considering Big-O Fundamentals?",
    options: ["Always memorize one canonical implementation and use it unchanged", "you must compare scalability of candidate solutions", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "you must compare scalability of candidate solutions This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-03",
    topicId: "complexity-analysis",
    prompt: "What is the most useful invariant to maintain when applying Big-O Fundamentals?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Big-O Fundamentals algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Big-O Fundamentals algorithm progresses This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-04",
    topicId: "complexity-analysis",
    prompt: "When using a standard efficient implementation of Big-O Fundamentals, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-05",
    topicId: "complexity-analysis",
    prompt: "Which memory cost is easiest to overlook when reasoning about Big-O Fundamentals?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-06",
    topicId: "complexity-analysis",
    prompt: "Which edge case should be checked explicitly in a robust Big-O Fundamentals solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-07",
    topicId: "complexity-analysis",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Big-O Fundamentals solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-08",
    topicId: "complexity-analysis",
    prompt: "What is the best reason to compare Big-O Fundamentals with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-09",
    topicId: "complexity-analysis",
    prompt: "Which input property can materially change how you implement Big-O Fundamentals?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-10",
    topicId: "complexity-analysis",
    prompt: "What should algorithmic state represent in a clean Big-O Fundamentals solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-11",
    topicId: "complexity-analysis",
    prompt: "What should guarantee termination in an iterative or recursive use of Big-O Fundamentals?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-12",
    topicId: "complexity-analysis",
    prompt: "What is the strongest way to reason about correctness for Big-O Fundamentals in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-13",
    topicId: "complexity-analysis",
    prompt: "Before optimizing a working Big-O Fundamentals solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-14",
    topicId: "complexity-analysis",
    prompt: "Which implementation habit most improves reliability for Big-O Fundamentals?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-15",
    topicId: "complexity-analysis",
    prompt: "Which test strategy is most useful for validating a Big-O Fundamentals implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-16",
    topicId: "complexity-analysis",
    prompt: "When should you avoid forcing Big-O Fundamentals onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Big-O Fundamentals correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Big-O Fundamentals correct or efficient This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-17",
    topicId: "complexity-analysis",
    prompt: "When explaining a Big-O Fundamentals solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-18",
    topicId: "complexity-analysis",
    prompt: "Why should constraints be examined before selecting Big-O Fundamentals?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-19",
    topicId: "complexity-analysis",
    prompt: "What is the main value of dry-running a Big-O Fundamentals solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
  {
    id: "complexity-analysis-20",
    topicId: "complexity-analysis",
    prompt: "After solving a Big-O Fundamentals problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Big-O Fundamentals.",
  },
];
