import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "hash-table-complexity",
    category: "big-o",
    title: "Hash Table Complexity",
    description: "Distinguish expected, average, and worst-case hash table behavior.",
    accent: "green",
    questionIds: ["hash-table-complexity-01", "hash-table-complexity-02", "hash-table-complexity-03", "hash-table-complexity-04", "hash-table-complexity-05", "hash-table-complexity-06", "hash-table-complexity-07", "hash-table-complexity-08", "hash-table-complexity-09", "hash-table-complexity-10", "hash-table-complexity-11", "hash-table-complexity-12", "hash-table-complexity-13", "hash-table-complexity-14", "hash-table-complexity-15", "hash-table-complexity-16", "hash-table-complexity-17", "hash-table-complexity-18", "hash-table-complexity-19", "hash-table-complexity-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "hash-table-complexity-01",
    topicId: "hash-table-complexity",
    prompt: "Which statement best describes the core purpose of Hash Table Complexity?",
    options: ["expected constant-time operations depend on hashing and controlled load, while worst-case collisions can degrade performance", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "expected constant-time operations depend on hashing and controlled load, while worst-case collisions can degrade performance This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-02",
    topicId: "hash-table-complexity",
    prompt: "Which interview clue most strongly suggests considering Hash Table Complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "a solution relies on map or set lookup complexity", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "a solution relies on map or set lookup complexity This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-03",
    topicId: "hash-table-complexity",
    prompt: "What is the most useful invariant to maintain when applying Hash Table Complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Hash Table Complexity algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Hash Table Complexity algorithm progresses This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-04",
    topicId: "hash-table-complexity",
    prompt: "When using a standard efficient implementation of Hash Table Complexity, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-05",
    topicId: "hash-table-complexity",
    prompt: "Which memory cost is easiest to overlook when reasoning about Hash Table Complexity?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-06",
    topicId: "hash-table-complexity",
    prompt: "Which edge case should be checked explicitly in a robust Hash Table Complexity solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-07",
    topicId: "hash-table-complexity",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Hash Table Complexity solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-08",
    topicId: "hash-table-complexity",
    prompt: "What is the best reason to compare Hash Table Complexity with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-09",
    topicId: "hash-table-complexity",
    prompt: "Which input property can materially change how you implement Hash Table Complexity?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-10",
    topicId: "hash-table-complexity",
    prompt: "What should algorithmic state represent in a clean Hash Table Complexity solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-11",
    topicId: "hash-table-complexity",
    prompt: "What should guarantee termination in an iterative or recursive use of Hash Table Complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-12",
    topicId: "hash-table-complexity",
    prompt: "What is the strongest way to reason about correctness for Hash Table Complexity in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-13",
    topicId: "hash-table-complexity",
    prompt: "Before optimizing a working Hash Table Complexity solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-14",
    topicId: "hash-table-complexity",
    prompt: "Which implementation habit most improves reliability for Hash Table Complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-15",
    topicId: "hash-table-complexity",
    prompt: "Which test strategy is most useful for validating a Hash Table Complexity implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-16",
    topicId: "hash-table-complexity",
    prompt: "When should you avoid forcing Hash Table Complexity onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Hash Table Complexity correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Hash Table Complexity correct or efficient This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-17",
    topicId: "hash-table-complexity",
    prompt: "When explaining a Hash Table Complexity solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-18",
    topicId: "hash-table-complexity",
    prompt: "Why should constraints be examined before selecting Hash Table Complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-19",
    topicId: "hash-table-complexity",
    prompt: "What is the main value of dry-running a Hash Table Complexity solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
  {
    id: "hash-table-complexity-20",
    topicId: "hash-table-complexity",
    prompt: "After solving a Hash Table Complexity problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Hash Table Complexity.",
  },
];
