import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "recurrence-complexity",
    category: "big-o",
    title: "Recursive Complexity",
    description: "Reason about recursion trees, branching, depth, and divide-and-conquer complexity.",
    accent: "coral",
    questionIds: ["recurrence-complexity-01", "recurrence-complexity-02", "recurrence-complexity-03", "recurrence-complexity-04", "recurrence-complexity-05", "recurrence-complexity-06", "recurrence-complexity-07", "recurrence-complexity-08", "recurrence-complexity-09", "recurrence-complexity-10", "recurrence-complexity-11", "recurrence-complexity-12", "recurrence-complexity-13", "recurrence-complexity-14", "recurrence-complexity-15", "recurrence-complexity-16", "recurrence-complexity-17", "recurrence-complexity-18", "recurrence-complexity-19", "recurrence-complexity-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "recurrence-complexity-01",
    topicId: "recurrence-complexity",
    prompt: "Which statement best describes the core purpose of Recursive Complexity?",
    options: ["branching factor, work per call, and recursion depth determine total work", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "branching factor, work per call, and recursion depth determine total work This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-02",
    topicId: "recurrence-complexity",
    prompt: "Which interview clue most strongly suggests considering Recursive Complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "runtime is defined by recursive calls on smaller inputs", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "runtime is defined by recursive calls on smaller inputs This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-03",
    topicId: "recurrence-complexity",
    prompt: "What is the most useful invariant to maintain when applying Recursive Complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Recursive Complexity algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Recursive Complexity algorithm progresses This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-04",
    topicId: "recurrence-complexity",
    prompt: "When using a standard efficient implementation of Recursive Complexity, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-05",
    topicId: "recurrence-complexity",
    prompt: "Which memory cost is easiest to overlook when reasoning about Recursive Complexity?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-06",
    topicId: "recurrence-complexity",
    prompt: "Which edge case should be checked explicitly in a robust Recursive Complexity solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-07",
    topicId: "recurrence-complexity",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Recursive Complexity solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-08",
    topicId: "recurrence-complexity",
    prompt: "What is the best reason to compare Recursive Complexity with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-09",
    topicId: "recurrence-complexity",
    prompt: "Which input property can materially change how you implement Recursive Complexity?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-10",
    topicId: "recurrence-complexity",
    prompt: "What should algorithmic state represent in a clean Recursive Complexity solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-11",
    topicId: "recurrence-complexity",
    prompt: "What should guarantee termination in an iterative or recursive use of Recursive Complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-12",
    topicId: "recurrence-complexity",
    prompt: "What is the strongest way to reason about correctness for Recursive Complexity in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-13",
    topicId: "recurrence-complexity",
    prompt: "Before optimizing a working Recursive Complexity solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-14",
    topicId: "recurrence-complexity",
    prompt: "Which implementation habit most improves reliability for Recursive Complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-15",
    topicId: "recurrence-complexity",
    prompt: "Which test strategy is most useful for validating a Recursive Complexity implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-16",
    topicId: "recurrence-complexity",
    prompt: "When should you avoid forcing Recursive Complexity onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Recursive Complexity correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Recursive Complexity correct or efficient This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-17",
    topicId: "recurrence-complexity",
    prompt: "When explaining a Recursive Complexity solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-18",
    topicId: "recurrence-complexity",
    prompt: "Why should constraints be examined before selecting Recursive Complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-19",
    topicId: "recurrence-complexity",
    prompt: "What is the main value of dry-running a Recursive Complexity solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Recursive Complexity.",
  },
  {
    id: "recurrence-complexity-20",
    topicId: "recurrence-complexity",
    prompt: "After solving a Recursive Complexity problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Recursive Complexity.",
  },
];
