import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "merge-sort",
    category: "concepts",
    title: "Merge Sort",
    description: "Understand divide-and-conquer sorting, merging, stability, and trade-offs.",
    accent: "blue",
    questionIds: ["merge-sort-01", "merge-sort-02", "merge-sort-03", "merge-sort-04", "merge-sort-05", "merge-sort-06", "merge-sort-07", "merge-sort-08", "merge-sort-09", "merge-sort-10", "merge-sort-11", "merge-sort-12", "merge-sort-13", "merge-sort-14", "merge-sort-15", "merge-sort-16", "merge-sort-17", "merge-sort-18", "merge-sort-19", "merge-sort-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "merge-sort-01",
    topicId: "merge-sort",
    prompt: "Which statement best describes the core purpose of Merge Sort?",
    options: ["sorted halves are recursively produced and merged in linear work per level", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "sorted halves are recursively produced and merged in linear work per level This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-02",
    topicId: "merge-sort",
    prompt: "Which interview clue most strongly suggests considering Merge Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "stable predictable O(n log n) sorting is useful", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "stable predictable O(n log n) sorting is useful This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-03",
    topicId: "merge-sort",
    prompt: "What is the most useful invariant to maintain when applying Merge Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Merge Sort algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Merge Sort algorithm progresses This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-04",
    topicId: "merge-sort",
    prompt: "When using a standard efficient implementation of Merge Sort, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-05",
    topicId: "merge-sort",
    prompt: "Which memory cost is easiest to overlook when reasoning about Merge Sort?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-06",
    topicId: "merge-sort",
    prompt: "Which edge case should be checked explicitly in a robust Merge Sort solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-07",
    topicId: "merge-sort",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Merge Sort solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-08",
    topicId: "merge-sort",
    prompt: "What is the best reason to compare Merge Sort with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-09",
    topicId: "merge-sort",
    prompt: "Which input property can materially change how you implement Merge Sort?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-10",
    topicId: "merge-sort",
    prompt: "What should algorithmic state represent in a clean Merge Sort solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-11",
    topicId: "merge-sort",
    prompt: "What should guarantee termination in an iterative or recursive use of Merge Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-12",
    topicId: "merge-sort",
    prompt: "What is the strongest way to reason about correctness for Merge Sort in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-13",
    topicId: "merge-sort",
    prompt: "Before optimizing a working Merge Sort solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-14",
    topicId: "merge-sort",
    prompt: "Which implementation habit most improves reliability for Merge Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-15",
    topicId: "merge-sort",
    prompt: "Which test strategy is most useful for validating a Merge Sort implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-16",
    topicId: "merge-sort",
    prompt: "When should you avoid forcing Merge Sort onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Merge Sort correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Merge Sort correct or efficient This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-17",
    topicId: "merge-sort",
    prompt: "When explaining a Merge Sort solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-18",
    topicId: "merge-sort",
    prompt: "Why should constraints be examined before selecting Merge Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-19",
    topicId: "merge-sort",
    prompt: "What is the main value of dry-running a Merge Sort solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Merge Sort.",
  },
  {
    id: "merge-sort-20",
    topicId: "merge-sort",
    prompt: "After solving a Merge Sort problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Merge Sort.",
  },
];
