import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "minimum-spanning-tree",
    category: "concepts",
    title: "Minimum Spanning Tree",
    description: "Understand Kruskal, Prim, cut intuition, and connectivity cost.",
    accent: "green",
    questionIds: ["minimum-spanning-tree-01", "minimum-spanning-tree-02", "minimum-spanning-tree-03", "minimum-spanning-tree-04", "minimum-spanning-tree-05", "minimum-spanning-tree-06", "minimum-spanning-tree-07", "minimum-spanning-tree-08", "minimum-spanning-tree-09", "minimum-spanning-tree-10", "minimum-spanning-tree-11", "minimum-spanning-tree-12", "minimum-spanning-tree-13", "minimum-spanning-tree-14", "minimum-spanning-tree-15", "minimum-spanning-tree-16", "minimum-spanning-tree-17", "minimum-spanning-tree-18", "minimum-spanning-tree-19", "minimum-spanning-tree-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "minimum-spanning-tree-01",
    topicId: "minimum-spanning-tree",
    prompt: "Which statement best describes the core purpose of Minimum Spanning Tree?",
    options: ["a minimum-cost acyclic set of edges connects all vertices", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "a minimum-cost acyclic set of edges connects all vertices This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-02",
    topicId: "minimum-spanning-tree",
    prompt: "Which interview clue most strongly suggests considering Minimum Spanning Tree?",
    options: ["Always memorize one canonical implementation and use it unchanged", "all vertices must be connected with minimum total edge cost", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "all vertices must be connected with minimum total edge cost This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-03",
    topicId: "minimum-spanning-tree",
    prompt: "What is the most useful invariant to maintain when applying Minimum Spanning Tree?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Minimum Spanning Tree algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Minimum Spanning Tree algorithm progresses This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-04",
    topicId: "minimum-spanning-tree",
    prompt: "When using a standard efficient implementation of Minimum Spanning Tree, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-05",
    topicId: "minimum-spanning-tree",
    prompt: "Which memory cost is easiest to overlook when reasoning about Minimum Spanning Tree?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-06",
    topicId: "minimum-spanning-tree",
    prompt: "Which edge case should be checked explicitly in a robust Minimum Spanning Tree solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-07",
    topicId: "minimum-spanning-tree",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Minimum Spanning Tree solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-08",
    topicId: "minimum-spanning-tree",
    prompt: "What is the best reason to compare Minimum Spanning Tree with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-09",
    topicId: "minimum-spanning-tree",
    prompt: "Which input property can materially change how you implement Minimum Spanning Tree?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-10",
    topicId: "minimum-spanning-tree",
    prompt: "What should algorithmic state represent in a clean Minimum Spanning Tree solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-11",
    topicId: "minimum-spanning-tree",
    prompt: "What should guarantee termination in an iterative or recursive use of Minimum Spanning Tree?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-12",
    topicId: "minimum-spanning-tree",
    prompt: "What is the strongest way to reason about correctness for Minimum Spanning Tree in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-13",
    topicId: "minimum-spanning-tree",
    prompt: "Before optimizing a working Minimum Spanning Tree solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-14",
    topicId: "minimum-spanning-tree",
    prompt: "Which implementation habit most improves reliability for Minimum Spanning Tree?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-15",
    topicId: "minimum-spanning-tree",
    prompt: "Which test strategy is most useful for validating a Minimum Spanning Tree implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-16",
    topicId: "minimum-spanning-tree",
    prompt: "When should you avoid forcing Minimum Spanning Tree onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Minimum Spanning Tree correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Minimum Spanning Tree correct or efficient This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-17",
    topicId: "minimum-spanning-tree",
    prompt: "When explaining a Minimum Spanning Tree solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-18",
    topicId: "minimum-spanning-tree",
    prompt: "Why should constraints be examined before selecting Minimum Spanning Tree?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-19",
    topicId: "minimum-spanning-tree",
    prompt: "What is the main value of dry-running a Minimum Spanning Tree solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
  {
    id: "minimum-spanning-tree-20",
    topicId: "minimum-spanning-tree",
    prompt: "After solving a Minimum Spanning Tree problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Minimum Spanning Tree.",
  },
];
