import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "quick-sort",
    category: "concepts",
    title: "Quick Sort",
    description: "Understand partitioning, pivot choice, average/worst cases, and in-place behavior.",
    accent: "coral",
    questionIds: ["quick-sort-01", "quick-sort-02", "quick-sort-03", "quick-sort-04", "quick-sort-05", "quick-sort-06", "quick-sort-07", "quick-sort-08", "quick-sort-09", "quick-sort-10", "quick-sort-11", "quick-sort-12", "quick-sort-13", "quick-sort-14", "quick-sort-15", "quick-sort-16", "quick-sort-17", "quick-sort-18", "quick-sort-19", "quick-sort-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "quick-sort-01",
    topicId: "quick-sort",
    prompt: "Which statement best describes the core purpose of Quick Sort?",
    options: ["partitioning places elements around a pivot before recursively sorting partitions", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "partitioning places elements around a pivot before recursively sorting partitions This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-02",
    topicId: "quick-sort",
    prompt: "Which interview clue most strongly suggests considering Quick Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "in-place average O(n log n) sorting with good practical locality is desired", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "in-place average O(n log n) sorting with good practical locality is desired This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-03",
    topicId: "quick-sort",
    prompt: "What is the most useful invariant to maintain when applying Quick Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Quick Sort algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Quick Sort algorithm progresses This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-04",
    topicId: "quick-sort",
    prompt: "When using a standard efficient implementation of Quick Sort, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-05",
    topicId: "quick-sort",
    prompt: "Which memory cost is easiest to overlook when reasoning about Quick Sort?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-06",
    topicId: "quick-sort",
    prompt: "Which edge case should be checked explicitly in a robust Quick Sort solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-07",
    topicId: "quick-sort",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Quick Sort solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-08",
    topicId: "quick-sort",
    prompt: "What is the best reason to compare Quick Sort with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-09",
    topicId: "quick-sort",
    prompt: "Which input property can materially change how you implement Quick Sort?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-10",
    topicId: "quick-sort",
    prompt: "What should algorithmic state represent in a clean Quick Sort solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-11",
    topicId: "quick-sort",
    prompt: "What should guarantee termination in an iterative or recursive use of Quick Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-12",
    topicId: "quick-sort",
    prompt: "What is the strongest way to reason about correctness for Quick Sort in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-13",
    topicId: "quick-sort",
    prompt: "Before optimizing a working Quick Sort solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-14",
    topicId: "quick-sort",
    prompt: "Which implementation habit most improves reliability for Quick Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-15",
    topicId: "quick-sort",
    prompt: "Which test strategy is most useful for validating a Quick Sort implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-16",
    topicId: "quick-sort",
    prompt: "When should you avoid forcing Quick Sort onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Quick Sort correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Quick Sort correct or efficient This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-17",
    topicId: "quick-sort",
    prompt: "When explaining a Quick Sort solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-18",
    topicId: "quick-sort",
    prompt: "Why should constraints be examined before selecting Quick Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-19",
    topicId: "quick-sort",
    prompt: "What is the main value of dry-running a Quick Sort solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Quick Sort.",
  },
  {
    id: "quick-sort-20",
    topicId: "quick-sort",
    prompt: "After solving a Quick Sort problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Quick Sort.",
  },
];
