import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "selection-sort",
    category: "concepts",
    title: "Selection Sort",
    description: "Review selection-based sorting, swaps, invariants, and complexity.",
    accent: "green",
    questionIds: ["selection-sort-01", "selection-sort-02", "selection-sort-03", "selection-sort-04", "selection-sort-05", "selection-sort-06", "selection-sort-07", "selection-sort-08", "selection-sort-09", "selection-sort-10", "selection-sort-11", "selection-sort-12", "selection-sort-13", "selection-sort-14", "selection-sort-15", "selection-sort-16", "selection-sort-17", "selection-sort-18", "selection-sort-19", "selection-sort-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "selection-sort-01",
    topicId: "selection-sort",
    prompt: "Which statement best describes the core purpose of Selection Sort?",
    options: ["each pass selects an extreme element for the next final position", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "each pass selects an extreme element for the next final position This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-02",
    topicId: "selection-sort",
    prompt: "Which interview clue most strongly suggests considering Selection Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "you are studying simple in-place comparison sorting with few swaps", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "you are studying simple in-place comparison sorting with few swaps This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-03",
    topicId: "selection-sort",
    prompt: "What is the most useful invariant to maintain when applying Selection Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Selection Sort algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Selection Sort algorithm progresses This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-04",
    topicId: "selection-sort",
    prompt: "When using a standard efficient implementation of Selection Sort, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-05",
    topicId: "selection-sort",
    prompt: "Which memory cost is easiest to overlook when reasoning about Selection Sort?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-06",
    topicId: "selection-sort",
    prompt: "Which edge case should be checked explicitly in a robust Selection Sort solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-07",
    topicId: "selection-sort",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Selection Sort solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-08",
    topicId: "selection-sort",
    prompt: "What is the best reason to compare Selection Sort with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-09",
    topicId: "selection-sort",
    prompt: "Which input property can materially change how you implement Selection Sort?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-10",
    topicId: "selection-sort",
    prompt: "What should algorithmic state represent in a clean Selection Sort solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-11",
    topicId: "selection-sort",
    prompt: "What should guarantee termination in an iterative or recursive use of Selection Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-12",
    topicId: "selection-sort",
    prompt: "What is the strongest way to reason about correctness for Selection Sort in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-13",
    topicId: "selection-sort",
    prompt: "Before optimizing a working Selection Sort solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-14",
    topicId: "selection-sort",
    prompt: "Which implementation habit most improves reliability for Selection Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-15",
    topicId: "selection-sort",
    prompt: "Which test strategy is most useful for validating a Selection Sort implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-16",
    topicId: "selection-sort",
    prompt: "When should you avoid forcing Selection Sort onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Selection Sort correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Selection Sort correct or efficient This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-17",
    topicId: "selection-sort",
    prompt: "When explaining a Selection Sort solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-18",
    topicId: "selection-sort",
    prompt: "Why should constraints be examined before selecting Selection Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-19",
    topicId: "selection-sort",
    prompt: "What is the main value of dry-running a Selection Sort solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Selection Sort.",
  },
  {
    id: "selection-sort-20",
    topicId: "selection-sort",
    prompt: "After solving a Selection Sort problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Selection Sort.",
  },
];
