import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "shortest-paths",
    category: "concepts",
    title: "Shortest Paths",
    description: "Choose BFS, Dijkstra, Bellman-Ford, or DAG techniques based on edge properties.",
    accent: "coral",
    questionIds: ["shortest-paths-01", "shortest-paths-02", "shortest-paths-03", "shortest-paths-04", "shortest-paths-05", "shortest-paths-06", "shortest-paths-07", "shortest-paths-08", "shortest-paths-09", "shortest-paths-10", "shortest-paths-11", "shortest-paths-12", "shortest-paths-13", "shortest-paths-14", "shortest-paths-15", "shortest-paths-16", "shortest-paths-17", "shortest-paths-18", "shortest-paths-19", "shortest-paths-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "shortest-paths-01",
    topicId: "shortest-paths",
    prompt: "Which statement best describes the core purpose of Shortest Paths?",
    options: ["the algorithm must match edge weights and graph properties", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "the algorithm must match edge weights and graph properties This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-02",
    topicId: "shortest-paths",
    prompt: "Which interview clue most strongly suggests considering Shortest Paths?",
    options: ["Always memorize one canonical implementation and use it unchanged", "the goal is minimum path cost or distance between graph states", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "the goal is minimum path cost or distance between graph states This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-03",
    topicId: "shortest-paths",
    prompt: "What is the most useful invariant to maintain when applying Shortest Paths?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Shortest Paths algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Shortest Paths algorithm progresses This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-04",
    topicId: "shortest-paths",
    prompt: "When using a standard efficient implementation of Shortest Paths, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-05",
    topicId: "shortest-paths",
    prompt: "Which memory cost is easiest to overlook when reasoning about Shortest Paths?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-06",
    topicId: "shortest-paths",
    prompt: "Which edge case should be checked explicitly in a robust Shortest Paths solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-07",
    topicId: "shortest-paths",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Shortest Paths solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-08",
    topicId: "shortest-paths",
    prompt: "What is the best reason to compare Shortest Paths with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-09",
    topicId: "shortest-paths",
    prompt: "Which input property can materially change how you implement Shortest Paths?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-10",
    topicId: "shortest-paths",
    prompt: "What should algorithmic state represent in a clean Shortest Paths solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-11",
    topicId: "shortest-paths",
    prompt: "What should guarantee termination in an iterative or recursive use of Shortest Paths?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-12",
    topicId: "shortest-paths",
    prompt: "What is the strongest way to reason about correctness for Shortest Paths in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-13",
    topicId: "shortest-paths",
    prompt: "Before optimizing a working Shortest Paths solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-14",
    topicId: "shortest-paths",
    prompt: "Which implementation habit most improves reliability for Shortest Paths?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-15",
    topicId: "shortest-paths",
    prompt: "Which test strategy is most useful for validating a Shortest Paths implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-16",
    topicId: "shortest-paths",
    prompt: "When should you avoid forcing Shortest Paths onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Shortest Paths correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Shortest Paths correct or efficient This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-17",
    topicId: "shortest-paths",
    prompt: "When explaining a Shortest Paths solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-18",
    topicId: "shortest-paths",
    prompt: "Why should constraints be examined before selecting Shortest Paths?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-19",
    topicId: "shortest-paths",
    prompt: "What is the main value of dry-running a Shortest Paths solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Shortest Paths.",
  },
  {
    id: "shortest-paths-20",
    topicId: "shortest-paths",
    prompt: "After solving a Shortest Paths problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Shortest Paths.",
  },
];
