import type { PracticeProblem } from "../types";

const defaultTemplate: Record<PracticeProblem["patternId"], string> = {
  "two-pointers": "two-pointers-opposite-ends",
  "sliding-window": "sliding-window-variable",
  "prefix-sum": "prefix-sum-build",
  "string-building": "string-building-array-join",
  "linked-list": "linked-list-fast-slow",
  "monotonic-stack": "monotonic-stack-increasing",
  "binary-search": "binary-search",
  "binary-tree": "binary-tree-dfs-recursive",
  graph: "graph-dfs-recursive",
  backtracking: "backtracking",
  "dynamic-programming": "dynamic-programming-top-down",
  trie: "trie-build",
  heap: "",
  "shortest-path": "",
};

const templateOverrides: Record<string, string> = {
  "tp-move-zeroes": "two-pointers-two-inputs",
  "ps-subarray-sum": "prefix-sum-exact-subarrays",
  "ps-shortest-subarray": "prefix-sum-exact-subarrays",
  "ps-product-except-self": "suffix-min-build",
  "sb-defang-ip": "string-building-concatenation",
  "sb-zigzag": "string-building-concatenation",
  "ll-merge-two": "linked-list-reverse",
  "ll-copy-random": "linked-list-reverse",
  "ll-merge-k": "linked-list-reverse",
  "ms-final-prices": "monotonic-stack-decreasing",
  "ms-remove-k-digits": "monotonic-stack-decreasing",
  "bs-search-insert": "binary-search-left",
  "bs-rotated": "binary-search-right",
  "bs-min-rotated": "binary-search-minimum",
  "bs-koko": "binary-search-minimum",
  "bs-median": "binary-search-maximum",
  "bt-level-order": "binary-tree-bfs",
  "bt-kth-smallest": "binary-tree-dfs-iterative",
  "g-town-judge": "graph-dfs-iterative",
  "g-clone": "graph-dfs-iterative",
  "g-word-ladder": "graph-bfs",
};

const problem = (
  id: string,
  patternId: PracticeProblem["patternId"],
  title: string,
  difficulty: PracticeProblem["difficulty"],
  slug: string,
): PracticeProblem => ({
  id,
  patternId,
  templateId: templateOverrides[id] ?? defaultTemplate[patternId],
  title,
  difficulty,
  url: `https://leetcode.com/problems/${slug}/`,
});

export const practiceProblems: PracticeProblem[] = [
  problem(
    "tp-valid-palindrome",
    "two-pointers",
    "Valid Palindrome",
    "Easy",
    "valid-palindrome",
  ),
  problem(
    "tp-move-zeroes",
    "two-pointers",
    "Move Zeroes",
    "Easy",
    "move-zeroes",
  ),
  problem(
    "tp-two-sum-ii",
    "two-pointers",
    "Two Sum II - Input Array Is Sorted",
    "Medium",
    "two-sum-ii-input-array-is-sorted",
  ),
  problem(
    "tp-container-water",
    "two-pointers",
    "Container With Most Water",
    "Medium",
    "container-with-most-water",
  ),
  problem("tp-three-sum", "two-pointers", "3Sum", "Medium", "3sum"),
  problem(
    "tp-trapping-rain-water",
    "two-pointers",
    "Trapping Rain Water",
    "Hard",
    "trapping-rain-water",
  ),

  problem(
    "sw-max-average",
    "sliding-window",
    "Maximum Average Subarray I",
    "Easy",
    "maximum-average-subarray-i",
  ),
  problem(
    "sw-contains-duplicate-ii",
    "sliding-window",
    "Contains Duplicate II",
    "Easy",
    "contains-duplicate-ii",
  ),
  problem(
    "sw-longest-substring",
    "sliding-window",
    "Longest Substring Without Repeating Characters",
    "Medium",
    "longest-substring-without-repeating-characters",
  ),
  problem(
    "sw-character-replacement",
    "sliding-window",
    "Longest Repeating Character Replacement",
    "Medium",
    "longest-repeating-character-replacement",
  ),
  problem(
    "sw-permutation-string",
    "sliding-window",
    "Permutation in String",
    "Medium",
    "permutation-in-string",
  ),
  problem(
    "sw-minimum-window",
    "sliding-window",
    "Minimum Window Substring",
    "Hard",
    "minimum-window-substring",
  ),

  problem(
    "ps-running-sum",
    "prefix-sum",
    "Running Sum of 1d Array",
    "Easy",
    "running-sum-of-1d-array",
  ),
  problem(
    "ps-pivot-index",
    "prefix-sum",
    "Find Pivot Index",
    "Easy",
    "find-pivot-index",
  ),
  problem(
    "ps-range-sum",
    "prefix-sum",
    "Range Sum Query - Immutable",
    "Medium",
    "range-sum-query-immutable",
  ),
  problem(
    "ps-subarray-sum",
    "prefix-sum",
    "Subarray Sum Equals K",
    "Medium",
    "subarray-sum-equals-k",
  ),
  problem(
    "ps-product-except-self",
    "prefix-sum",
    "Product of Array Except Self",
    "Medium",
    "product-of-array-except-self",
  ),
  problem(
    "ps-shortest-subarray",
    "prefix-sum",
    "Shortest Subarray with Sum at Least K",
    "Hard",
    "shortest-subarray-with-sum-at-least-k",
  ),

  problem(
    "sb-reverse-string",
    "string-building",
    "Reverse String",
    "Easy",
    "reverse-string",
  ),
  problem(
    "sb-defang-ip",
    "string-building",
    "Defanging an IP Address",
    "Easy",
    "defanging-an-ip-address",
  ),
  problem(
    "sb-zigzag",
    "string-building",
    "Zigzag Conversion",
    "Medium",
    "zigzag-conversion",
  ),
  problem(
    "sb-string-compression",
    "string-building",
    "String Compression",
    "Medium",
    "string-compression",
  ),
  problem(
    "sb-decode-string",
    "string-building",
    "Decode String",
    "Medium",
    "decode-string",
  ),
  problem(
    "sb-text-justification",
    "string-building",
    "Text Justification",
    "Hard",
    "text-justification",
  ),

  problem(
    "ll-merge-two",
    "linked-list",
    "Merge Two Sorted Lists",
    "Easy",
    "merge-two-sorted-lists",
  ),
  problem(
    "ll-cycle",
    "linked-list",
    "Linked List Cycle",
    "Easy",
    "linked-list-cycle",
  ),
  problem(
    "ll-remove-nth",
    "linked-list",
    "Remove Nth Node From End of List",
    "Medium",
    "remove-nth-node-from-end-of-list",
  ),
  problem(
    "ll-reorder",
    "linked-list",
    "Reorder List",
    "Medium",
    "reorder-list",
  ),
  problem(
    "ll-copy-random",
    "linked-list",
    "Copy List with Random Pointer",
    "Medium",
    "copy-list-with-random-pointer",
  ),
  problem(
    "ll-merge-k",
    "linked-list",
    "Merge k Sorted Lists",
    "Hard",
    "merge-k-sorted-lists",
  ),

  problem(
    "ms-next-greater-i",
    "monotonic-stack",
    "Next Greater Element I",
    "Easy",
    "next-greater-element-i",
  ),
  problem(
    "ms-final-prices",
    "monotonic-stack",
    "Final Prices With a Special Discount in a Shop",
    "Easy",
    "final-prices-with-a-special-discount-in-a-shop",
  ),
  problem(
    "ms-daily-temperatures",
    "monotonic-stack",
    "Daily Temperatures",
    "Medium",
    "daily-temperatures",
  ),
  problem(
    "ms-stock-span",
    "monotonic-stack",
    "Online Stock Span",
    "Medium",
    "online-stock-span",
  ),
  problem(
    "ms-remove-k-digits",
    "monotonic-stack",
    "Remove K Digits",
    "Medium",
    "remove-k-digits",
  ),
  problem(
    "ms-largest-rectangle",
    "monotonic-stack",
    "Largest Rectangle in Histogram",
    "Hard",
    "largest-rectangle-in-histogram",
  ),

  problem(
    "bs-search",
    "binary-search",
    "Binary Search",
    "Easy",
    "binary-search",
  ),
  problem(
    "bs-search-insert",
    "binary-search",
    "Search Insert Position",
    "Easy",
    "search-insert-position",
  ),
  problem(
    "bs-rotated",
    "binary-search",
    "Search in Rotated Sorted Array",
    "Medium",
    "search-in-rotated-sorted-array",
  ),
  problem(
    "bs-min-rotated",
    "binary-search",
    "Find Minimum in Rotated Sorted Array",
    "Medium",
    "find-minimum-in-rotated-sorted-array",
  ),
  problem(
    "bs-koko",
    "binary-search",
    "Koko Eating Bananas",
    "Medium",
    "koko-eating-bananas",
  ),
  problem(
    "bs-median",
    "binary-search",
    "Median of Two Sorted Arrays",
    "Hard",
    "median-of-two-sorted-arrays",
  ),

  problem(
    "bt-max-depth",
    "binary-tree",
    "Maximum Depth of Binary Tree",
    "Easy",
    "maximum-depth-of-binary-tree",
  ),
  problem(
    "bt-invert",
    "binary-tree",
    "Invert Binary Tree",
    "Easy",
    "invert-binary-tree",
  ),
  problem(
    "bt-level-order",
    "binary-tree",
    "Binary Tree Level Order Traversal",
    "Medium",
    "binary-tree-level-order-traversal",
  ),
  problem(
    "bt-validate-bst",
    "binary-tree",
    "Validate Binary Search Tree",
    "Medium",
    "validate-binary-search-tree",
  ),
  problem(
    "bt-kth-smallest",
    "binary-tree",
    "Kth Smallest Element in a BST",
    "Medium",
    "kth-smallest-element-in-a-bst",
  ),
  problem(
    "bt-serialize",
    "binary-tree",
    "Serialize and Deserialize Binary Tree",
    "Hard",
    "serialize-and-deserialize-binary-tree",
  ),

  problem(
    "g-find-center",
    "graph",
    "Find Center of Star Graph",
    "Easy",
    "find-center-of-star-graph",
  ),
  problem(
    "g-town-judge",
    "graph",
    "Find the Town Judge",
    "Easy",
    "find-the-town-judge",
  ),
  problem(
    "g-islands",
    "graph",
    "Number of Islands",
    "Medium",
    "number-of-islands",
  ),
  problem("g-clone", "graph", "Clone Graph", "Medium", "clone-graph"),
  problem(
    "g-course-schedule",
    "graph",
    "Course Schedule",
    "Medium",
    "course-schedule",
  ),
  problem("g-word-ladder", "graph", "Word Ladder", "Hard", "word-ladder"),

  problem(
    "b-letter-case",
    "backtracking",
    "Letter Case Permutation",
    "Easy",
    "letter-case-permutation",
  ),
  problem(
    "b-binary-watch",
    "backtracking",
    "Binary Watch",
    "Easy",
    "binary-watch",
  ),
  problem("b-subsets", "backtracking", "Subsets", "Medium", "subsets"),
  problem(
    "b-combination-sum",
    "backtracking",
    "Combination Sum",
    "Medium",
    "combination-sum",
  ),
  problem(
    "b-word-search",
    "backtracking",
    "Word Search",
    "Medium",
    "word-search",
  ),
  problem("b-n-queens", "backtracking", "N-Queens", "Hard", "n-queens"),

  problem(
    "dp-climbing-stairs",
    "dynamic-programming",
    "Climbing Stairs",
    "Easy",
    "climbing-stairs",
  ),
  problem(
    "dp-min-cost",
    "dynamic-programming",
    "Min Cost Climbing Stairs",
    "Easy",
    "min-cost-climbing-stairs",
  ),
  problem(
    "dp-house-robber",
    "dynamic-programming",
    "House Robber",
    "Medium",
    "house-robber",
  ),
  problem(
    "dp-coin-change",
    "dynamic-programming",
    "Coin Change",
    "Medium",
    "coin-change",
  ),
  problem(
    "dp-longest-increasing",
    "dynamic-programming",
    "Longest Increasing Subsequence",
    "Medium",
    "longest-increasing-subsequence",
  ),
  problem(
    "dp-edit-distance",
    "dynamic-programming",
    "Edit Distance",
    "Hard",
    "edit-distance",
  ),

  problem(
    "trie-longest-prefix",
    "trie",
    "Longest Common Prefix",
    "Easy",
    "longest-common-prefix",
  ),
  problem(
    "trie-replace-words",
    "trie",
    "Replace Words",
    "Easy",
    "replace-words",
  ),
  problem(
    "trie-implement",
    "trie",
    "Implement Trie (Prefix Tree)",
    "Medium",
    "implement-trie-prefix-tree",
  ),
  problem(
    "trie-design-search",
    "trie",
    "Design Add and Search Words Data Structure",
    "Medium",
    "design-add-and-search-words-data-structure",
  ),
  problem("trie-map-sum", "trie", "Map Sum Pairs", "Medium", "map-sum-pairs"),
  problem(
    "trie-word-search-ii",
    "trie",
    "Word Search II",
    "Hard",
    "word-search-ii",
  ),
];

export const getProblemsForPattern = (
  patternId: PracticeProblem["patternId"],
) => practiceProblems.filter((item) => item.patternId === patternId);

export const getProblemsForTemplate = (templateId: string) =>
  practiceProblems.filter((item) => item.templateId === templateId);
