import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "arrays-hashing",
    category: "patterns",
    title: "Arrays & Hashing",
    description: "Recognize array and hash-based techniques, trade-offs, and interview patterns.",
    accent: "coral",
    questionIds: ["arrays-hashing-01", "arrays-hashing-02", "arrays-hashing-03", "arrays-hashing-04", "arrays-hashing-05", "arrays-hashing-06", "arrays-hashing-07", "arrays-hashing-08", "arrays-hashing-09", "arrays-hashing-10", "arrays-hashing-11", "arrays-hashing-12", "arrays-hashing-13", "arrays-hashing-14", "arrays-hashing-15", "arrays-hashing-16", "arrays-hashing-17", "arrays-hashing-18", "arrays-hashing-19", "arrays-hashing-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "arrays-hashing-01",
    topicId: "arrays-hashing",
    prompt: "Which statement best describes the core purpose of Arrays & Hashing?",
    options: ["direct indexing or hash-based lookup can replace repeated scanning", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "direct indexing or hash-based lookup can replace repeated scanning This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-02",
    topicId: "arrays-hashing",
    prompt: "Which interview clue most strongly suggests considering Arrays & Hashing?",
    options: ["Always memorize one canonical implementation and use it unchanged", "fast membership, frequency, grouping, or complement lookup is needed", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "fast membership, frequency, grouping, or complement lookup is needed This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-03",
    topicId: "arrays-hashing",
    prompt: "What is the most useful invariant to maintain when applying Arrays & Hashing?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Arrays & Hashing algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Arrays & Hashing algorithm progresses This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-04",
    topicId: "arrays-hashing",
    prompt: "When using a standard efficient implementation of Arrays & Hashing, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-05",
    topicId: "arrays-hashing",
    prompt: "Which memory cost is easiest to overlook when reasoning about Arrays & Hashing?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-06",
    topicId: "arrays-hashing",
    prompt: "Which edge case should be checked explicitly in a robust Arrays & Hashing solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-07",
    topicId: "arrays-hashing",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Arrays & Hashing solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-08",
    topicId: "arrays-hashing",
    prompt: "What is the best reason to compare Arrays & Hashing with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-09",
    topicId: "arrays-hashing",
    prompt: "Which input property can materially change how you implement Arrays & Hashing?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-10",
    topicId: "arrays-hashing",
    prompt: "What should algorithmic state represent in a clean Arrays & Hashing solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-11",
    topicId: "arrays-hashing",
    prompt: "What should guarantee termination in an iterative or recursive use of Arrays & Hashing?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-12",
    topicId: "arrays-hashing",
    prompt: "What is the strongest way to reason about correctness for Arrays & Hashing in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-13",
    topicId: "arrays-hashing",
    prompt: "Before optimizing a working Arrays & Hashing solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-14",
    topicId: "arrays-hashing",
    prompt: "Which implementation habit most improves reliability for Arrays & Hashing?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-15",
    topicId: "arrays-hashing",
    prompt: "Which test strategy is most useful for validating a Arrays & Hashing implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-16",
    topicId: "arrays-hashing",
    prompt: "When should you avoid forcing Arrays & Hashing onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Arrays & Hashing correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Arrays & Hashing correct or efficient This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-17",
    topicId: "arrays-hashing",
    prompt: "When explaining a Arrays & Hashing solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-18",
    topicId: "arrays-hashing",
    prompt: "Why should constraints be examined before selecting Arrays & Hashing?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-19",
    topicId: "arrays-hashing",
    prompt: "What is the main value of dry-running a Arrays & Hashing solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
  {
    id: "arrays-hashing-20",
    topicId: "arrays-hashing",
    prompt: "After solving a Arrays & Hashing problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Arrays & Hashing.",
  },
];
