import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "backtracking",
    category: "patterns",
    title: "Backtracking",
    description: "Explore decision trees using choose-explore-unchoose and pruning.",
    accent: "amber",
    questionIds: ["backtracking-01", "backtracking-02", "backtracking-03", "backtracking-04", "backtracking-05", "backtracking-06", "backtracking-07", "backtracking-08", "backtracking-09", "backtracking-10", "backtracking-11", "backtracking-12", "backtracking-13", "backtracking-14", "backtracking-15", "backtracking-16", "backtracking-17", "backtracking-18", "backtracking-19", "backtracking-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "backtracking-01",
    topicId: "backtracking",
    prompt: "Which statement best describes the core purpose of Backtracking?",
    options: ["a decision tree is explored while choices are undone after each branch", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "a decision tree is explored while choices are undone after each branch This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-02",
    topicId: "backtracking",
    prompt: "Which interview clue most strongly suggests considering Backtracking?",
    options: ["Always memorize one canonical implementation and use it unchanged", "you must enumerate combinations, permutations, placements, or constrained choices", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "you must enumerate combinations, permutations, placements, or constrained choices This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-03",
    topicId: "backtracking",
    prompt: "What is the most useful invariant to maintain when applying Backtracking?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Backtracking algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Backtracking algorithm progresses This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-04",
    topicId: "backtracking",
    prompt: "When using a standard efficient implementation of Backtracking, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-05",
    topicId: "backtracking",
    prompt: "Which memory cost is easiest to overlook when reasoning about Backtracking?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-06",
    topicId: "backtracking",
    prompt: "Which edge case should be checked explicitly in a robust Backtracking solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-07",
    topicId: "backtracking",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Backtracking solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-08",
    topicId: "backtracking",
    prompt: "What is the best reason to compare Backtracking with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-09",
    topicId: "backtracking",
    prompt: "Which input property can materially change how you implement Backtracking?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-10",
    topicId: "backtracking",
    prompt: "What should algorithmic state represent in a clean Backtracking solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-11",
    topicId: "backtracking",
    prompt: "What should guarantee termination in an iterative or recursive use of Backtracking?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-12",
    topicId: "backtracking",
    prompt: "What is the strongest way to reason about correctness for Backtracking in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-13",
    topicId: "backtracking",
    prompt: "Before optimizing a working Backtracking solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-14",
    topicId: "backtracking",
    prompt: "Which implementation habit most improves reliability for Backtracking?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-15",
    topicId: "backtracking",
    prompt: "Which test strategy is most useful for validating a Backtracking implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-16",
    topicId: "backtracking",
    prompt: "When should you avoid forcing Backtracking onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Backtracking correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Backtracking correct or efficient This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-17",
    topicId: "backtracking",
    prompt: "When explaining a Backtracking solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-18",
    topicId: "backtracking",
    prompt: "Why should constraints be examined before selecting Backtracking?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-19",
    topicId: "backtracking",
    prompt: "What is the main value of dry-running a Backtracking solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Backtracking.",
  },
  {
    id: "backtracking-20",
    topicId: "backtracking",
    prompt: "After solving a Backtracking problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Backtracking.",
  },
];
