import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "binary-search",
    category: "patterns",
    title: "Binary Search",
    description: "Master search-space reduction, boundaries, variants, and binary search on answers.",
    accent: "coral",
    questionIds: ["binary-search-01", "binary-search-02", "binary-search-03", "binary-search-04", "binary-search-05", "binary-search-06", "binary-search-07", "binary-search-08", "binary-search-09", "binary-search-10", "binary-search-11", "binary-search-12", "binary-search-13", "binary-search-14", "binary-search-15", "binary-search-16", "binary-search-17", "binary-search-18", "binary-search-19", "binary-search-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "binary-search-01",
    topicId: "binary-search",
    prompt: "Which statement best describes the core purpose of Binary Search?",
    options: ["each decision discards a large portion of an ordered or monotonic search space", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "each decision discards a large portion of an ordered or monotonic search space This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-02",
    topicId: "binary-search",
    prompt: "Which interview clue most strongly suggests considering Binary Search?",
    options: ["Always memorize one canonical implementation and use it unchanged", "a sorted domain or monotonic predicate lets you eliminate half the candidates", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "a sorted domain or monotonic predicate lets you eliminate half the candidates This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-03",
    topicId: "binary-search",
    prompt: "What is the most useful invariant to maintain when applying Binary Search?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Binary Search algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Binary Search algorithm progresses This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-04",
    topicId: "binary-search",
    prompt: "When using a standard efficient implementation of Binary Search, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-05",
    topicId: "binary-search",
    prompt: "Which memory cost is easiest to overlook when reasoning about Binary Search?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-06",
    topicId: "binary-search",
    prompt: "Which edge case should be checked explicitly in a robust Binary Search solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-07",
    topicId: "binary-search",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Binary Search solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-08",
    topicId: "binary-search",
    prompt: "What is the best reason to compare Binary Search with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-09",
    topicId: "binary-search",
    prompt: "Which input property can materially change how you implement Binary Search?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-10",
    topicId: "binary-search",
    prompt: "What should algorithmic state represent in a clean Binary Search solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-11",
    topicId: "binary-search",
    prompt: "What should guarantee termination in an iterative or recursive use of Binary Search?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-12",
    topicId: "binary-search",
    prompt: "What is the strongest way to reason about correctness for Binary Search in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-13",
    topicId: "binary-search",
    prompt: "Before optimizing a working Binary Search solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-14",
    topicId: "binary-search",
    prompt: "Which implementation habit most improves reliability for Binary Search?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-15",
    topicId: "binary-search",
    prompt: "Which test strategy is most useful for validating a Binary Search implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-16",
    topicId: "binary-search",
    prompt: "When should you avoid forcing Binary Search onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Binary Search correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Binary Search correct or efficient This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-17",
    topicId: "binary-search",
    prompt: "When explaining a Binary Search solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-18",
    topicId: "binary-search",
    prompt: "Why should constraints be examined before selecting Binary Search?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-19",
    topicId: "binary-search",
    prompt: "What is the main value of dry-running a Binary Search solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Binary Search.",
  },
  {
    id: "binary-search-20",
    topicId: "binary-search",
    prompt: "After solving a Binary Search problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Binary Search.",
  },
];
