import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "dfs",
    category: "patterns",
    title: "Depth-First Search",
    description: "Use recursive and iterative depth-first exploration, state, and backtracking.",
    accent: "blue",
    questionIds: ["dfs-01", "dfs-02", "dfs-03", "dfs-04", "dfs-05", "dfs-06", "dfs-07", "dfs-08", "dfs-09", "dfs-10", "dfs-11", "dfs-12", "dfs-13", "dfs-14", "dfs-15", "dfs-16", "dfs-17", "dfs-18", "dfs-19", "dfs-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "dfs-01",
    topicId: "dfs",
    prompt: "Which statement best describes the core purpose of Depth-First Search?",
    options: ["one path is explored deeply before alternatives, naturally matching recursive structure", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "one path is explored deeply before alternatives, naturally matching recursive structure This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-02",
    topicId: "dfs",
    prompt: "Which interview clue most strongly suggests considering Depth-First Search?",
    options: ["Always memorize one canonical implementation and use it unchanged", "you need exhaustive reachability, component, path, or subtree exploration", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "you need exhaustive reachability, component, path, or subtree exploration This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-03",
    topicId: "dfs",
    prompt: "What is the most useful invariant to maintain when applying Depth-First Search?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Depth-First Search algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Depth-First Search algorithm progresses This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-04",
    topicId: "dfs",
    prompt: "When using a standard efficient implementation of Depth-First Search, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-05",
    topicId: "dfs",
    prompt: "Which memory cost is easiest to overlook when reasoning about Depth-First Search?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-06",
    topicId: "dfs",
    prompt: "Which edge case should be checked explicitly in a robust Depth-First Search solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-07",
    topicId: "dfs",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Depth-First Search solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-08",
    topicId: "dfs",
    prompt: "What is the best reason to compare Depth-First Search with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-09",
    topicId: "dfs",
    prompt: "Which input property can materially change how you implement Depth-First Search?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-10",
    topicId: "dfs",
    prompt: "What should algorithmic state represent in a clean Depth-First Search solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-11",
    topicId: "dfs",
    prompt: "What should guarantee termination in an iterative or recursive use of Depth-First Search?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-12",
    topicId: "dfs",
    prompt: "What is the strongest way to reason about correctness for Depth-First Search in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-13",
    topicId: "dfs",
    prompt: "Before optimizing a working Depth-First Search solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-14",
    topicId: "dfs",
    prompt: "Which implementation habit most improves reliability for Depth-First Search?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-15",
    topicId: "dfs",
    prompt: "Which test strategy is most useful for validating a Depth-First Search implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-16",
    topicId: "dfs",
    prompt: "When should you avoid forcing Depth-First Search onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Depth-First Search correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Depth-First Search correct or efficient This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-17",
    topicId: "dfs",
    prompt: "When explaining a Depth-First Search solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-18",
    topicId: "dfs",
    prompt: "Why should constraints be examined before selecting Depth-First Search?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-19",
    topicId: "dfs",
    prompt: "What is the main value of dry-running a Depth-First Search solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Depth-First Search.",
  },
  {
    id: "dfs-20",
    topicId: "dfs",
    prompt: "After solving a Depth-First Search problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Depth-First Search.",
  },
];
