import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "divide-conquer",
    category: "patterns",
    title: "Divide & Conquer",
    description: "Split problems into independent subproblems and combine their results.",
    accent: "green",
    questionIds: ["divide-conquer-01", "divide-conquer-02", "divide-conquer-03", "divide-conquer-04", "divide-conquer-05", "divide-conquer-06", "divide-conquer-07", "divide-conquer-08", "divide-conquer-09", "divide-conquer-10", "divide-conquer-11", "divide-conquer-12", "divide-conquer-13", "divide-conquer-14", "divide-conquer-15", "divide-conquer-16", "divide-conquer-17", "divide-conquer-18", "divide-conquer-19", "divide-conquer-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "divide-conquer-01",
    topicId: "divide-conquer",
    prompt: "Which statement best describes the core purpose of Divide & Conquer?",
    options: ["independent smaller subproblems are solved and their results combined", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "independent smaller subproblems are solved and their results combined This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-02",
    topicId: "divide-conquer",
    prompt: "Which interview clue most strongly suggests considering Divide & Conquer?",
    options: ["Always memorize one canonical implementation and use it unchanged", "the input can be split into similar largely independent parts", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "the input can be split into similar largely independent parts This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-03",
    topicId: "divide-conquer",
    prompt: "What is the most useful invariant to maintain when applying Divide & Conquer?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Divide & Conquer algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Divide & Conquer algorithm progresses This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-04",
    topicId: "divide-conquer",
    prompt: "When using a standard efficient implementation of Divide & Conquer, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-05",
    topicId: "divide-conquer",
    prompt: "Which memory cost is easiest to overlook when reasoning about Divide & Conquer?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-06",
    topicId: "divide-conquer",
    prompt: "Which edge case should be checked explicitly in a robust Divide & Conquer solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-07",
    topicId: "divide-conquer",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Divide & Conquer solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-08",
    topicId: "divide-conquer",
    prompt: "What is the best reason to compare Divide & Conquer with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-09",
    topicId: "divide-conquer",
    prompt: "Which input property can materially change how you implement Divide & Conquer?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-10",
    topicId: "divide-conquer",
    prompt: "What should algorithmic state represent in a clean Divide & Conquer solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-11",
    topicId: "divide-conquer",
    prompt: "What should guarantee termination in an iterative or recursive use of Divide & Conquer?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-12",
    topicId: "divide-conquer",
    prompt: "What is the strongest way to reason about correctness for Divide & Conquer in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-13",
    topicId: "divide-conquer",
    prompt: "Before optimizing a working Divide & Conquer solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-14",
    topicId: "divide-conquer",
    prompt: "Which implementation habit most improves reliability for Divide & Conquer?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-15",
    topicId: "divide-conquer",
    prompt: "Which test strategy is most useful for validating a Divide & Conquer implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-16",
    topicId: "divide-conquer",
    prompt: "When should you avoid forcing Divide & Conquer onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Divide & Conquer correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Divide & Conquer correct or efficient This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-17",
    topicId: "divide-conquer",
    prompt: "When explaining a Divide & Conquer solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-18",
    topicId: "divide-conquer",
    prompt: "Why should constraints be examined before selecting Divide & Conquer?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-19",
    topicId: "divide-conquer",
    prompt: "What is the main value of dry-running a Divide & Conquer solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Divide & Conquer.",
  },
  {
    id: "divide-conquer-20",
    topicId: "divide-conquer",
    prompt: "After solving a Divide & Conquer problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Divide & Conquer.",
  },
];
