import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "dynamic-programming-2d",
    category: "patterns",
    title: "2D Dynamic Programming",
    description: "Model grid, sequence, and multi-dimensional state transitions.",
    accent: "blue",
    questionIds: ["dynamic-programming-2d-01", "dynamic-programming-2d-02", "dynamic-programming-2d-03", "dynamic-programming-2d-04", "dynamic-programming-2d-05", "dynamic-programming-2d-06", "dynamic-programming-2d-07", "dynamic-programming-2d-08", "dynamic-programming-2d-09", "dynamic-programming-2d-10", "dynamic-programming-2d-11", "dynamic-programming-2d-12", "dynamic-programming-2d-13", "dynamic-programming-2d-14", "dynamic-programming-2d-15", "dynamic-programming-2d-16", "dynamic-programming-2d-17", "dynamic-programming-2d-18", "dynamic-programming-2d-19", "dynamic-programming-2d-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "dynamic-programming-2d-01",
    topicId: "dynamic-programming-2d",
    prompt: "Which statement best describes the core purpose of 2D Dynamic Programming?",
    options: ["a state with two changing dimensions captures overlapping subproblems", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "a state with two changing dimensions captures overlapping subproblems This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-02",
    topicId: "dynamic-programming-2d",
    prompt: "Which interview clue most strongly suggests considering 2D Dynamic Programming?",
    options: ["Always memorize one canonical implementation and use it unchanged", "the problem relates two indices, sequences, grid coordinates, or capacities", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "the problem relates two indices, sequences, grid coordinates, or capacities This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-03",
    topicId: "dynamic-programming-2d",
    prompt: "What is the most useful invariant to maintain when applying 2D Dynamic Programming?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the 2D Dynamic Programming algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the 2D Dynamic Programming algorithm progresses This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-04",
    topicId: "dynamic-programming-2d",
    prompt: "When using a standard efficient implementation of 2D Dynamic Programming, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-05",
    topicId: "dynamic-programming-2d",
    prompt: "Which memory cost is easiest to overlook when reasoning about 2D Dynamic Programming?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-06",
    topicId: "dynamic-programming-2d",
    prompt: "Which edge case should be checked explicitly in a robust 2D Dynamic Programming solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-07",
    topicId: "dynamic-programming-2d",
    prompt: "Which mistake most commonly breaks an otherwise reasonable 2D Dynamic Programming solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-08",
    topicId: "dynamic-programming-2d",
    prompt: "What is the best reason to compare 2D Dynamic Programming with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-09",
    topicId: "dynamic-programming-2d",
    prompt: "Which input property can materially change how you implement 2D Dynamic Programming?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-10",
    topicId: "dynamic-programming-2d",
    prompt: "What should algorithmic state represent in a clean 2D Dynamic Programming solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-11",
    topicId: "dynamic-programming-2d",
    prompt: "What should guarantee termination in an iterative or recursive use of 2D Dynamic Programming?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-12",
    topicId: "dynamic-programming-2d",
    prompt: "What is the strongest way to reason about correctness for 2D Dynamic Programming in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-13",
    topicId: "dynamic-programming-2d",
    prompt: "Before optimizing a working 2D Dynamic Programming solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-14",
    topicId: "dynamic-programming-2d",
    prompt: "Which implementation habit most improves reliability for 2D Dynamic Programming?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-15",
    topicId: "dynamic-programming-2d",
    prompt: "Which test strategy is most useful for validating a 2D Dynamic Programming implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-16",
    topicId: "dynamic-programming-2d",
    prompt: "When should you avoid forcing 2D Dynamic Programming onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make 2D Dynamic Programming correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make 2D Dynamic Programming correct or efficient This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-17",
    topicId: "dynamic-programming-2d",
    prompt: "When explaining a 2D Dynamic Programming solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-18",
    topicId: "dynamic-programming-2d",
    prompt: "Why should constraints be examined before selecting 2D Dynamic Programming?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-19",
    topicId: "dynamic-programming-2d",
    prompt: "What is the main value of dry-running a 2D Dynamic Programming solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
  {
    id: "dynamic-programming-2d-20",
    topicId: "dynamic-programming-2d",
    prompt: "After solving a 2D Dynamic Programming problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for 2D Dynamic Programming.",
  },
];
