import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "greedy",
    category: "patterns",
    title: "Greedy",
    description: "Identify locally optimal choices, proof intuition, and when greedy fails.",
    accent: "coral",
    questionIds: ["greedy-01", "greedy-02", "greedy-03", "greedy-04", "greedy-05", "greedy-06", "greedy-07", "greedy-08", "greedy-09", "greedy-10", "greedy-11", "greedy-12", "greedy-13", "greedy-14", "greedy-15", "greedy-16", "greedy-17", "greedy-18", "greedy-19", "greedy-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "greedy-01",
    topicId: "greedy",
    prompt: "Which statement best describes the core purpose of Greedy?",
    options: ["a locally optimal choice is committed when an exchange or dominance argument makes it safe", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "a locally optimal choice is committed when an exchange or dominance argument makes it safe This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-02",
    topicId: "greedy",
    prompt: "Which interview clue most strongly suggests considering Greedy?",
    options: ["Always memorize one canonical implementation and use it unchanged", "the problem has a provably safe local choice that need not be revisited", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "the problem has a provably safe local choice that need not be revisited This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-03",
    topicId: "greedy",
    prompt: "What is the most useful invariant to maintain when applying Greedy?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Greedy algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Greedy algorithm progresses This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-04",
    topicId: "greedy",
    prompt: "When using a standard efficient implementation of Greedy, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-05",
    topicId: "greedy",
    prompt: "Which memory cost is easiest to overlook when reasoning about Greedy?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-06",
    topicId: "greedy",
    prompt: "Which edge case should be checked explicitly in a robust Greedy solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-07",
    topicId: "greedy",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Greedy solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-08",
    topicId: "greedy",
    prompt: "What is the best reason to compare Greedy with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-09",
    topicId: "greedy",
    prompt: "Which input property can materially change how you implement Greedy?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-10",
    topicId: "greedy",
    prompt: "What should algorithmic state represent in a clean Greedy solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-11",
    topicId: "greedy",
    prompt: "What should guarantee termination in an iterative or recursive use of Greedy?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-12",
    topicId: "greedy",
    prompt: "What is the strongest way to reason about correctness for Greedy in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-13",
    topicId: "greedy",
    prompt: "Before optimizing a working Greedy solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-14",
    topicId: "greedy",
    prompt: "Which implementation habit most improves reliability for Greedy?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-15",
    topicId: "greedy",
    prompt: "Which test strategy is most useful for validating a Greedy implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-16",
    topicId: "greedy",
    prompt: "When should you avoid forcing Greedy onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Greedy correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Greedy correct or efficient This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-17",
    topicId: "greedy",
    prompt: "When explaining a Greedy solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-18",
    topicId: "greedy",
    prompt: "Why should constraints be examined before selecting Greedy?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-19",
    topicId: "greedy",
    prompt: "What is the main value of dry-running a Greedy solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Greedy.",
  },
  {
    id: "greedy-20",
    topicId: "greedy",
    prompt: "After solving a Greedy problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Greedy.",
  },
];
