import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "knapsack",
    category: "patterns",
    title: "Knapsack Patterns",
    description: "Recognize 0/1, unbounded, subset-sum, and capacity-based DP.",
    accent: "coral",
    questionIds: ["knapsack-01", "knapsack-02", "knapsack-03", "knapsack-04", "knapsack-05", "knapsack-06", "knapsack-07", "knapsack-08", "knapsack-09", "knapsack-10", "knapsack-11", "knapsack-12", "knapsack-13", "knapsack-14", "knapsack-15", "knapsack-16", "knapsack-17", "knapsack-18", "knapsack-19", "knapsack-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "knapsack-01",
    topicId: "knapsack",
    prompt: "Which statement best describes the core purpose of Knapsack Patterns?",
    options: ["state tracks achievable value or feasibility under a capacity-like constraint", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "state tracks achievable value or feasibility under a capacity-like constraint This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-02",
    topicId: "knapsack",
    prompt: "Which interview clue most strongly suggests considering Knapsack Patterns?",
    options: ["Always memorize one canonical implementation and use it unchanged", "items are chosen under capacity, target sum, or reuse restrictions", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "items are chosen under capacity, target sum, or reuse restrictions This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-03",
    topicId: "knapsack",
    prompt: "What is the most useful invariant to maintain when applying Knapsack Patterns?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Knapsack Patterns algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Knapsack Patterns algorithm progresses This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-04",
    topicId: "knapsack",
    prompt: "When using a standard efficient implementation of Knapsack Patterns, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-05",
    topicId: "knapsack",
    prompt: "Which memory cost is easiest to overlook when reasoning about Knapsack Patterns?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-06",
    topicId: "knapsack",
    prompt: "Which edge case should be checked explicitly in a robust Knapsack Patterns solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-07",
    topicId: "knapsack",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Knapsack Patterns solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-08",
    topicId: "knapsack",
    prompt: "What is the best reason to compare Knapsack Patterns with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-09",
    topicId: "knapsack",
    prompt: "Which input property can materially change how you implement Knapsack Patterns?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-10",
    topicId: "knapsack",
    prompt: "What should algorithmic state represent in a clean Knapsack Patterns solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-11",
    topicId: "knapsack",
    prompt: "What should guarantee termination in an iterative or recursive use of Knapsack Patterns?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-12",
    topicId: "knapsack",
    prompt: "What is the strongest way to reason about correctness for Knapsack Patterns in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-13",
    topicId: "knapsack",
    prompt: "Before optimizing a working Knapsack Patterns solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-14",
    topicId: "knapsack",
    prompt: "Which implementation habit most improves reliability for Knapsack Patterns?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-15",
    topicId: "knapsack",
    prompt: "Which test strategy is most useful for validating a Knapsack Patterns implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-16",
    topicId: "knapsack",
    prompt: "When should you avoid forcing Knapsack Patterns onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Knapsack Patterns correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Knapsack Patterns correct or efficient This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-17",
    topicId: "knapsack",
    prompt: "When explaining a Knapsack Patterns solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-18",
    topicId: "knapsack",
    prompt: "Why should constraints be examined before selecting Knapsack Patterns?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-19",
    topicId: "knapsack",
    prompt: "What is the main value of dry-running a Knapsack Patterns solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
  {
    id: "knapsack-20",
    topicId: "knapsack",
    prompt: "After solving a Knapsack Patterns problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Knapsack Patterns.",
  },
];
