import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "monotonic-queue",
    category: "patterns",
    title: "Monotonic Queue",
    description: "Maintain window extrema efficiently with an ordered deque.",
    accent: "blue",
    questionIds: ["monotonic-queue-01", "monotonic-queue-02", "monotonic-queue-03", "monotonic-queue-04", "monotonic-queue-05", "monotonic-queue-06", "monotonic-queue-07", "monotonic-queue-08", "monotonic-queue-09", "monotonic-queue-10", "monotonic-queue-11", "monotonic-queue-12", "monotonic-queue-13", "monotonic-queue-14", "monotonic-queue-15", "monotonic-queue-16", "monotonic-queue-17", "monotonic-queue-18", "monotonic-queue-19", "monotonic-queue-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "monotonic-queue-01",
    topicId: "monotonic-queue",
    prompt: "Which statement best describes the core purpose of Monotonic Queue?",
    options: ["a deque removes dominated candidates while preserving the best value for a moving window", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "a deque removes dominated candidates while preserving the best value for a moving window This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-02",
    topicId: "monotonic-queue",
    prompt: "Which interview clue most strongly suggests considering Monotonic Queue?",
    options: ["Always memorize one canonical implementation and use it unchanged", "you need repeated min or max over a sliding window", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "you need repeated min or max over a sliding window This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-03",
    topicId: "monotonic-queue",
    prompt: "What is the most useful invariant to maintain when applying Monotonic Queue?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Monotonic Queue algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Monotonic Queue algorithm progresses This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-04",
    topicId: "monotonic-queue",
    prompt: "When using a standard efficient implementation of Monotonic Queue, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-05",
    topicId: "monotonic-queue",
    prompt: "Which memory cost is easiest to overlook when reasoning about Monotonic Queue?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-06",
    topicId: "monotonic-queue",
    prompt: "Which edge case should be checked explicitly in a robust Monotonic Queue solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-07",
    topicId: "monotonic-queue",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Monotonic Queue solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-08",
    topicId: "monotonic-queue",
    prompt: "What is the best reason to compare Monotonic Queue with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-09",
    topicId: "monotonic-queue",
    prompt: "Which input property can materially change how you implement Monotonic Queue?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-10",
    topicId: "monotonic-queue",
    prompt: "What should algorithmic state represent in a clean Monotonic Queue solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-11",
    topicId: "monotonic-queue",
    prompt: "What should guarantee termination in an iterative or recursive use of Monotonic Queue?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-12",
    topicId: "monotonic-queue",
    prompt: "What is the strongest way to reason about correctness for Monotonic Queue in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-13",
    topicId: "monotonic-queue",
    prompt: "Before optimizing a working Monotonic Queue solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-14",
    topicId: "monotonic-queue",
    prompt: "Which implementation habit most improves reliability for Monotonic Queue?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-15",
    topicId: "monotonic-queue",
    prompt: "Which test strategy is most useful for validating a Monotonic Queue implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-16",
    topicId: "monotonic-queue",
    prompt: "When should you avoid forcing Monotonic Queue onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Monotonic Queue correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Monotonic Queue correct or efficient This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-17",
    topicId: "monotonic-queue",
    prompt: "When explaining a Monotonic Queue solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-18",
    topicId: "monotonic-queue",
    prompt: "Why should constraints be examined before selecting Monotonic Queue?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-19",
    topicId: "monotonic-queue",
    prompt: "What is the main value of dry-running a Monotonic Queue solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Monotonic Queue.",
  },
  {
    id: "monotonic-queue-20",
    topicId: "monotonic-queue",
    prompt: "After solving a Monotonic Queue problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Monotonic Queue.",
  },
];
