import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "prefix-sums",
    category: "patterns",
    title: "Prefix Sums",
    description: "Use cumulative aggregates for fast range and subarray reasoning.",
    accent: "blue",
    questionIds: ["prefix-sums-01", "prefix-sums-02", "prefix-sums-03", "prefix-sums-04", "prefix-sums-05", "prefix-sums-06", "prefix-sums-07", "prefix-sums-08", "prefix-sums-09", "prefix-sums-10", "prefix-sums-11", "prefix-sums-12", "prefix-sums-13", "prefix-sums-14", "prefix-sums-15", "prefix-sums-16", "prefix-sums-17", "prefix-sums-18", "prefix-sums-19", "prefix-sums-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "prefix-sums-01",
    topicId: "prefix-sums",
    prompt: "Which statement best describes the core purpose of Prefix Sums?",
    options: ["precomputed cumulative values turn repeated range sums into constant-time queries", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "precomputed cumulative values turn repeated range sums into constant-time queries This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-02",
    topicId: "prefix-sums",
    prompt: "Which interview clue most strongly suggests considering Prefix Sums?",
    options: ["Always memorize one canonical implementation and use it unchanged", "many range or subarray aggregate queries are required", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "many range or subarray aggregate queries are required This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-03",
    topicId: "prefix-sums",
    prompt: "What is the most useful invariant to maintain when applying Prefix Sums?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Prefix Sums algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Prefix Sums algorithm progresses This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-04",
    topicId: "prefix-sums",
    prompt: "When using a standard efficient implementation of Prefix Sums, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-05",
    topicId: "prefix-sums",
    prompt: "Which memory cost is easiest to overlook when reasoning about Prefix Sums?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-06",
    topicId: "prefix-sums",
    prompt: "Which edge case should be checked explicitly in a robust Prefix Sums solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-07",
    topicId: "prefix-sums",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Prefix Sums solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-08",
    topicId: "prefix-sums",
    prompt: "What is the best reason to compare Prefix Sums with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-09",
    topicId: "prefix-sums",
    prompt: "Which input property can materially change how you implement Prefix Sums?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-10",
    topicId: "prefix-sums",
    prompt: "What should algorithmic state represent in a clean Prefix Sums solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-11",
    topicId: "prefix-sums",
    prompt: "What should guarantee termination in an iterative or recursive use of Prefix Sums?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-12",
    topicId: "prefix-sums",
    prompt: "What is the strongest way to reason about correctness for Prefix Sums in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-13",
    topicId: "prefix-sums",
    prompt: "Before optimizing a working Prefix Sums solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-14",
    topicId: "prefix-sums",
    prompt: "Which implementation habit most improves reliability for Prefix Sums?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-15",
    topicId: "prefix-sums",
    prompt: "Which test strategy is most useful for validating a Prefix Sums implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-16",
    topicId: "prefix-sums",
    prompt: "When should you avoid forcing Prefix Sums onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Prefix Sums correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Prefix Sums correct or efficient This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-17",
    topicId: "prefix-sums",
    prompt: "When explaining a Prefix Sums solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-18",
    topicId: "prefix-sums",
    prompt: "Why should constraints be examined before selecting Prefix Sums?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-19",
    topicId: "prefix-sums",
    prompt: "What is the main value of dry-running a Prefix Sums solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Prefix Sums.",
  },
  {
    id: "prefix-sums-20",
    topicId: "prefix-sums",
    prompt: "After solving a Prefix Sums problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Prefix Sums.",
  },
];
