import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "sliding-window",
    category: "patterns",
    title: "Sliding Window",
    description: "Recognize fixed and variable windows, frequency tracking, and window invariants.",
    accent: "amber",
    questionIds: ["sliding-window-01", "sliding-window-02", "sliding-window-03", "sliding-window-04", "sliding-window-05", "sliding-window-06", "sliding-window-07", "sliding-window-08", "sliding-window-09", "sliding-window-10", "sliding-window-11", "sliding-window-12", "sliding-window-13", "sliding-window-14", "sliding-window-15", "sliding-window-16", "sliding-window-17", "sliding-window-18", "sliding-window-19", "sliding-window-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "sliding-window-01",
    topicId: "sliding-window",
    prompt: "Which statement best describes the core purpose of Sliding Window?",
    options: ["a contiguous range is updated incrementally as its boundaries move", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "a contiguous range is updated incrementally as its boundaries move This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-02",
    topicId: "sliding-window",
    prompt: "Which interview clue most strongly suggests considering Sliding Window?",
    options: ["Always memorize one canonical implementation and use it unchanged", "the problem asks about a best or valid contiguous subarray or substring", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "the problem asks about a best or valid contiguous subarray or substring This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-03",
    topicId: "sliding-window",
    prompt: "What is the most useful invariant to maintain when applying Sliding Window?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Sliding Window algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Sliding Window algorithm progresses This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-04",
    topicId: "sliding-window",
    prompt: "When using a standard efficient implementation of Sliding Window, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-05",
    topicId: "sliding-window",
    prompt: "Which memory cost is easiest to overlook when reasoning about Sliding Window?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-06",
    topicId: "sliding-window",
    prompt: "Which edge case should be checked explicitly in a robust Sliding Window solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-07",
    topicId: "sliding-window",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Sliding Window solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-08",
    topicId: "sliding-window",
    prompt: "What is the best reason to compare Sliding Window with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-09",
    topicId: "sliding-window",
    prompt: "Which input property can materially change how you implement Sliding Window?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-10",
    topicId: "sliding-window",
    prompt: "What should algorithmic state represent in a clean Sliding Window solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-11",
    topicId: "sliding-window",
    prompt: "What should guarantee termination in an iterative or recursive use of Sliding Window?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-12",
    topicId: "sliding-window",
    prompt: "What is the strongest way to reason about correctness for Sliding Window in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-13",
    topicId: "sliding-window",
    prompt: "Before optimizing a working Sliding Window solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-14",
    topicId: "sliding-window",
    prompt: "Which implementation habit most improves reliability for Sliding Window?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-15",
    topicId: "sliding-window",
    prompt: "Which test strategy is most useful for validating a Sliding Window implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-16",
    topicId: "sliding-window",
    prompt: "When should you avoid forcing Sliding Window onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Sliding Window correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Sliding Window correct or efficient This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-17",
    topicId: "sliding-window",
    prompt: "When explaining a Sliding Window solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-18",
    topicId: "sliding-window",
    prompt: "Why should constraints be examined before selecting Sliding Window?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-19",
    topicId: "sliding-window",
    prompt: "What is the main value of dry-running a Sliding Window solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Sliding Window.",
  },
  {
    id: "sliding-window-20",
    topicId: "sliding-window",
    prompt: "After solving a Sliding Window problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Sliding Window.",
  },
];
