import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "topological-sort",
    category: "patterns",
    title: "Topological Sort",
    description: "Handle dependency ordering and cycle detection in directed acyclic graphs.",
    accent: "amber",
    questionIds: ["topological-sort-01", "topological-sort-02", "topological-sort-03", "topological-sort-04", "topological-sort-05", "topological-sort-06", "topological-sort-07", "topological-sort-08", "topological-sort-09", "topological-sort-10", "topological-sort-11", "topological-sort-12", "topological-sort-13", "topological-sort-14", "topological-sort-15", "topological-sort-16", "topological-sort-17", "topological-sort-18", "topological-sort-19", "topological-sort-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "topological-sort-01",
    topicId: "topological-sort",
    prompt: "Which statement best describes the core purpose of Topological Sort?",
    options: ["indegree or DFS ordering produces a dependency-respecting order only for DAGs", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "indegree or DFS ordering produces a dependency-respecting order only for DAGs This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-02",
    topicId: "topological-sort",
    prompt: "Which interview clue most strongly suggests considering Topological Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "tasks have directed prerequisites and you need a valid ordering", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "tasks have directed prerequisites and you need a valid ordering This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-03",
    topicId: "topological-sort",
    prompt: "What is the most useful invariant to maintain when applying Topological Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Topological Sort algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Topological Sort algorithm progresses This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-04",
    topicId: "topological-sort",
    prompt: "When using a standard efficient implementation of Topological Sort, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-05",
    topicId: "topological-sort",
    prompt: "Which memory cost is easiest to overlook when reasoning about Topological Sort?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-06",
    topicId: "topological-sort",
    prompt: "Which edge case should be checked explicitly in a robust Topological Sort solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-07",
    topicId: "topological-sort",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Topological Sort solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-08",
    topicId: "topological-sort",
    prompt: "What is the best reason to compare Topological Sort with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-09",
    topicId: "topological-sort",
    prompt: "Which input property can materially change how you implement Topological Sort?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-10",
    topicId: "topological-sort",
    prompt: "What should algorithmic state represent in a clean Topological Sort solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-11",
    topicId: "topological-sort",
    prompt: "What should guarantee termination in an iterative or recursive use of Topological Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-12",
    topicId: "topological-sort",
    prompt: "What is the strongest way to reason about correctness for Topological Sort in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-13",
    topicId: "topological-sort",
    prompt: "Before optimizing a working Topological Sort solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-14",
    topicId: "topological-sort",
    prompt: "Which implementation habit most improves reliability for Topological Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-15",
    topicId: "topological-sort",
    prompt: "Which test strategy is most useful for validating a Topological Sort implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-16",
    topicId: "topological-sort",
    prompt: "When should you avoid forcing Topological Sort onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Topological Sort correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Topological Sort correct or efficient This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-17",
    topicId: "topological-sort",
    prompt: "When explaining a Topological Sort solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-18",
    topicId: "topological-sort",
    prompt: "Why should constraints be examined before selecting Topological Sort?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-19",
    topicId: "topological-sort",
    prompt: "What is the main value of dry-running a Topological Sort solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Topological Sort.",
  },
  {
    id: "topological-sort-20",
    topicId: "topological-sort",
    prompt: "After solving a Topological Sort problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Topological Sort.",
  },
];
