import type { QuizQuestion, QuizTopic } from "../../../types";

export const topic: QuizTopic = {
    id: "two-pointers",
    category: "patterns",
    title: "Two Pointers",
    description: "Practice pointer movement, invariants, sorted-input clues, and common two-pointer problems.",
    accent: "green",
    questionIds: ["two-pointers-01", "two-pointers-02", "two-pointers-03", "two-pointers-04", "two-pointers-05", "two-pointers-06", "two-pointers-07", "two-pointers-08", "two-pointers-09", "two-pointers-10", "two-pointers-11", "two-pointers-12", "two-pointers-13", "two-pointers-14", "two-pointers-15", "two-pointers-16", "two-pointers-17", "two-pointers-18", "two-pointers-19", "two-pointers-20"],
  };

export const questions: QuizQuestion[] = [
  {
    id: "two-pointers-01",
    topicId: "two-pointers",
    prompt: "Which statement best describes the core purpose of Two Pointers?",
    options: ["two indices move according to an invariant instead of exploring all pairs", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "two indices move according to an invariant instead of exploring all pairs This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-02",
    topicId: "two-pointers",
    prompt: "Which interview clue most strongly suggests considering Two Pointers?",
    options: ["Always memorize one canonical implementation and use it unchanged", "the input is ordered or the problem compares elements from two ends", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "the input is ordered or the problem compares elements from two ends This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-03",
    topicId: "two-pointers",
    prompt: "What is the most useful invariant to maintain when applying Two Pointers?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Maintain a condition that remains true as the Two Pointers algorithm progresses", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Maintain a condition that remains true as the Two Pointers algorithm progresses This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-04",
    topicId: "two-pointers",
    prompt: "When using a standard efficient implementation of Two Pointers, what should you analyze first to justify its time complexity?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Count how many times each input element or state can participate in the dominant work"],
    correctOption: 3,
    explanation: "Count how many times each input element or state can participate in the dominant work This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-05",
    topicId: "two-pointers",
    prompt: "Which memory cost is easiest to overlook when reasoning about Two Pointers?",
    options: ["Auxiliary structures plus recursion/call-stack usage, not only the returned output", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Auxiliary structures plus recursion/call-stack usage, not only the returned output This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-06",
    topicId: "two-pointers",
    prompt: "Which edge case should be checked explicitly in a robust Two Pointers solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Empty/minimal input, boundary positions, duplicates, and other constraint-relevant extremes This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-07",
    topicId: "two-pointers",
    prompt: "Which mistake most commonly breaks an otherwise reasonable Two Pointers solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Changing state without preserving the condition that made earlier decisions valid", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Changing state without preserving the condition that made earlier decisions valid This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-08",
    topicId: "two-pointers",
    prompt: "What is the best reason to compare Two Pointers with an alternative approach before coding?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Different approaches can have different correctness assumptions, time, space, and implementation risk"],
    correctOption: 3,
    explanation: "Different approaches can have different correctness assumptions, time, space, and implementation risk This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-09",
    topicId: "two-pointers",
    prompt: "Which input property can materially change how you implement Two Pointers?",
    options: ["Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "Whether the data is sorted, weighted, contiguous, mutable, bounded, or otherwise structured This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-10",
    topicId: "two-pointers",
    prompt: "What should algorithmic state represent in a clean Two Pointers solution?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Only the information needed to make future decisions and avoid recomputing solved work", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Only the information needed to make future decisions and avoid recomputing solved work This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-11",
    topicId: "two-pointers",
    prompt: "What should guarantee termination in an iterative or recursive use of Two Pointers?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Each step must make measurable progress toward a base case or exhausted search space", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Each step must make measurable progress toward a base case or exhausted search space This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-12",
    topicId: "two-pointers",
    prompt: "What is the strongest way to reason about correctness for Two Pointers in an interview?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "State an invariant or induction-style argument showing each transition preserves validity"],
    correctOption: 3,
    explanation: "State an invariant or induction-style argument showing each transition preserves validity This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-13",
    topicId: "two-pointers",
    prompt: "Before optimizing a working Two Pointers solution, what should you identify?",
    options: ["The actual bottleneck in time or memory under the given constraints", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The actual bottleneck in time or memory under the given constraints This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-14",
    topicId: "two-pointers",
    prompt: "Which implementation habit most improves reliability for Two Pointers?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Use explicit names for state/boundaries and update them in one logically consistent place", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Use explicit names for state/boundaries and update them in one logically consistent place This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-15",
    topicId: "two-pointers",
    prompt: "Which test strategy is most useful for validating a Two Pointers implementation?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "Test tiny cases, boundary cases, duplicates, adversarial structure, and a normal representative case This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-16",
    topicId: "two-pointers",
    prompt: "When should you avoid forcing Two Pointers onto a problem?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "When the problem lacks the assumptions or structure that make Two Pointers correct or efficient"],
    correctOption: 3,
    explanation: "When the problem lacks the assumptions or structure that make Two Pointers correct or efficient This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-17",
    topicId: "two-pointers",
    prompt: "When explaining a Two Pointers solution, what should you communicate before writing code?",
    options: ["The recognition clue, invariant/state meaning, algorithm steps, and expected complexity", "Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 0,
    explanation: "The recognition clue, invariant/state meaning, algorithm steps, and expected complexity This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-18",
    topicId: "two-pointers",
    prompt: "Why should constraints be examined before selecting Two Pointers?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Constraints determine whether brute force passes and which time/space trade-offs are acceptable", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 1,
    explanation: "Constraints determine whether brute force passes and which time/space trade-offs are acceptable This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-19",
    topicId: "two-pointers",
    prompt: "What is the main value of dry-running a Two Pointers solution on a small example?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "It exposes state transitions, boundary errors, and whether the invariant remains true", "Assume all operations are constant time and ignore auxiliary memory"],
    correctOption: 2,
    explanation: "It exposes state transitions, boundary errors, and whether the invariant remains true This is the interview-relevant principle to remember for Two Pointers.",
  },
  {
    id: "two-pointers-20",
    topicId: "two-pointers",
    prompt: "After solving a Two Pointers problem, which review question best improves interview readiness?",
    options: ["Always memorize one canonical implementation and use it unchanged", "Choose the approach with the shortest source code regardless of constraints", "Assume all operations are constant time and ignore auxiliary memory", "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code?"],
    correctOption: 3,
    explanation: "Could I recognize the pattern earlier, explain why it works, and derive its complexity without memorizing code? This is the interview-relevant principle to remember for Two Pointers.",
  },
];
